# Generated by Django 3.2.2 on 2021-05-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0001_initial'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='train_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
    ]
