# Generated by Django 3.2.2 on 2021-05-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_rename_seats_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='car_number',
        ),
    ]
