# Generated by Django 3.2.2 on 2021-05-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
        ('station', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrive_order', models.IntegerField(default=1)),
                ('travel_time', models.IntegerField(default=0)),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('station_name', models.ForeignKey(default='forgoten station', on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
