# Generated by Django 3.2.3 on 2021-05-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrive_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
