# Generated by Django 3.2.2 on 2021-05-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_station_name'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='station.station'),
        ),
    ]
