# Generated by Django 3.2.3 on 2021-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210516_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='travel_time',
            field=models.IntegerField(default=0),
        ),
    ]
