# Generated by Django 3.2.2 on 2021-05-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='arrive_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='train_id',
        ),
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='route',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station'),
        ),
    ]
