# Generated by Django 3.2.2 on 2021-05-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20210516_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='arrive_order',
        ),
        migrations.RemoveField(
            model_name='route',
            name='station',
        ),
    ]
