# Generated by Django 3.2.2 on 2021-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(default='forgeten station', max_length=60)),
                ('station_distance', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
