# Generated by Django 3.2.2 on 2021-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(default=0),
        ),
    ]
