# Generated by Django 3.2.2 on 2021-05-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_station_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_id']},
        ),
    ]
