# Generated by Django 3.2.2 on 2021-05-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_station_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
    ]
