# Generated by Django 3.2.2 on 2021-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_alter_station_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='name',
        ),
    ]
