# Generated by Django 3.2.3 on 2021-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='type your name in', max_length=60)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
