# Generated by Django 3.2.2 on 2021-05-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('train', '__first__'),
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='Type your name in', max_length=60)),
                ('customer_id', models.CharField(default='0000000000', max_length=10)),
                ('customer_phone', models.CharField(default='Customer phone number', max_length=200)),
                ('ticket_type', models.CharField(blank=True, choices=[('One-way', 'One-way'), ('Return-trip', 'Return-trip')], max_length=255, null=True, verbose_name='ticket type')),
                ('price', models.FloatField(default=0.0, verbose_name='Price (in thousands dong)')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('departing_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Departure', to='station.station')),
                ('destination_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='station.station')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
    ]
