# Generated by Django 3.2.2 on 2021-05-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='departing_station',
            new_name='departing_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='destination',
            new_name='destination_id',
        ),
    ]
