# Generated by Django 3.2.3 on 2021-05-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='added_on',
            new_name='created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('WAITING', 'WAITING'), ('DONE', 'DONE')], max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(default='Type your name in', max_length=60),
        ),
    ]
