# Generated by Django 3.2.3 on 2021-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210515_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='closed_date',
            new_name='bought_in',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('TAKEN', 'TAKEN'), ('PAID', 'PAID')], max_length=255, null=True, verbose_name='Status'),
        ),
    ]
