# Generated by Django 3.2.3 on 2021-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210515_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.CharField(default='Note', max_length=255),
        ),
    ]
