# Generated by Django 3.2.3 on 2021-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.CharField(default='Where to?', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='starting_station',
            field=models.CharField(default='Where from?', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('One-way', 'One-way'), ('Round-trip', 'Round-trip')], max_length=255, null=True, verbose_name='ticket_type'),
        ),
    ]
