# Generated by Django 3.2.3 on 2021-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20210515_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_of_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0, verbose_name='thousands dong'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('One-way', 'One-way'), ('Round-trip', 'Round-trip')], max_length=255, null=True, verbose_name='ticket type'),
        ),
    ]
