# Generated by Django 3.2.3 on 2021-05-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20210515_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price (in thousands dong)'),
        ),
    ]
