# Generated by Django 3.2.3 on 2021-05-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('ticket', '0010_alter_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='starting_station',
        ),
        migrations.AddField(
            model_name='ticket',
            name='departing_station',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Departure', to='station.station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='station.station'),
        ),
    ]
