# Generated by Django 3.2.3 on 2021-05-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_rename_seats_seat'),
        ('train', '0001_initial'),
        ('ticket', '0011_auto_20210516_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='note',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seat.seat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='train_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='train.train'),
            preserve_default=False,
        ),
    ]
