# Generated by Django 3.2.3 on 2021-05-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20210516_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
