from tkinter import *
from PIL import ImageTk, Image
from datetime import datetime

root = Tk()
root.title('Good Job!')
root.geometry('1000x800') #wxh
root.maxsize(width=1000, height=800)
root.minsize(width=1000, height=700)
#Mystyle MyColor
blue = '#%02x%02x%02x' % (42,42,123)
weightedblue = '#%02x%02x%02x' % (0,0,102)
green = '#%02x%02x%02x' % (48, 191, 81)
grey = '#%02x%02x%02x' % (208,208,208)
lightedgrey = '#%02x%02x%02x' % (235, 235, 235)
lightblack = '#%02x%02x%02x' % (42,42,42)
large_font = ('Verdana',23)
medium_font = ('Verdana',15)
small_font = ('Verdana',11)
#function homebodyframe/findbodyframe/findseatbodyframe
def homepage():
    findbodyframe.pack_forget()
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack_forget()
    firstpageframe.pack()
    secondpageframe.pack_forget()
    thirdpageframe.pack_forget()
    homebodyframe.pack(fill=X)
def findtrip():
    homebodyframe.pack_forget()
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack_forget()
    firstpageframe.pack()
    secondpageframe.pack_forget()
    thirdpageframe.pack_forget()
    findbodyframe.pack(fill=X, ipady=50)
def findseat():
    homebodyframe.pack_forget()
    findbodyframe.pack_forget()
    findseatbodyframe.pack(fill=X, ipady=40)
def userinfo():
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack(fill=X, ipady=35)
def payment():
    firstpageframe.pack_forget()
    secondpageframe.pack()
def completed():
    secondpageframe.pack_forget()
    thirdpageframe.pack()

def changecolor1():
    seatbtn1.config(image=redimg)
    print(type(seatbtn1.cget("text")))
    print(seatbtn1.cget("text"))
def changecolor2():
    seatbtn2.config(image=redimg)
    print(type(seatbtn2.cget("text")))
    print(seatbtn2.cget("text"))
def changecolor3():
    seatbtn3.config(image=redimg)
    print(type(seatbtn3.cget("text")))
    print(seatbtn3.cget("text"))
def changecolor4():
    seatbtn4.config(image=redimg)
    print(type(seatbtn4.cget("text")))
    print(seatbtn4.cget("text"))
def changecolor5():
    seatbtn5.config(image=redimg)
    print(type(seatbtn5.cget("text")))
    print(seatbtn5.cget("text"))
def changecolor6():
    seatbtn6.config(image=redimg)
    print(type(seatbtn6.cget("text")))
    print(seatbtn6.cget("text"))
def changecolor7():
    seatbtn7.config(image=redimg)
    print(type(seatbtn7.cget("text")))
    print(seatbtn7.cget("text"))
def changecolor8():
    seatbtn8.config(image=redimg)
    print(type(seatbtn8.cget("text")))
    print(seatbtn8.cget("text"))
def changecolor9():
    seatbtn9.config(image=redimg)
    print(type(seatbtn9.cget("text")))
    print(seatbtn9.cget("text"))
def changecolor10():
    seatbtn10.config(image=redimg)
    print(type(seatbtn10.cget("text")))
    print(seatbtn10.cget("text"))
def changecolor11():
    seatbtn11.config(image=redimg)
    print(type(seatbtn11.cget("text")))
    print(seatbtn11.cget("text"))
def changecolor12():
    seatbtn12.config(image=redimg)
    print(type(seatbtn12.cget("text")))
    print(seatbtn12.cget("text"))
def changecolor13():
    seatbtn13.config(image=redimg)
    print(type(seatbtn13.cget("text")))
    print(seatbtn13.cget("text"))
def changecolor14():
    seatbtn14.config(image=redimg)
    print(type(seatbtn14.cget("text")))
    print(seatbtn14.cget("text"))
def changecolor15():
    seatbtn15.config(image=redimg)
    print(type(seatbtn15.cget("text")))
    print(seatbtn15.cget("text"))
def changecolor16():
    seatbtn16.config(image=redimg)
    print(type(seatbtn16.cget("text")))
    print(seatbtn16.cget("text"))
def changecolor17():
    seatbtn17.config(image=redimg)
    print(type(seatbtn17.cget("text")))
    print(seatbtn17.cget("text"))
def changecolor18():
    seatbtn18.config(image=redimg)
    print(type(seatbtn18.cget("text")))
    print(seatbtn18.cget("text"))
def changecolor19():
    seatbtn19.config(image=redimg)
    print(type(seatbtn19.cget("text")))
    print(seatbtn19.cget("text"))
def changecolor20():
    seatbtn20.config(image=redimg)
    print(type(seatbtn20.cget("text")))
    print(seatbtn20.cget("text"))
def changecolor21():
    seatbtn21.config(image=redimg)
    print(type(seatbtn21.cget("text")))
    print(seatbtn21.cget("text"))
def changecolor22():
    seatbtn22.config(image=redimg)
    print(type(seatbtn22.cget("text")))
    print(seatbtn22.cget("text"))
def changecolor23():
    seatbtn23.config(image=redimg)
    print(type(seatbtn23.cget("text")))
    print(seatbtn23.cget("text"))
def changecolor24():
    seatbtn24.config(image=redimg)
    print(type(seatbtn24.cget("text")))
    print(seatbtn24.cget("text"))
def changecolor25():
    seatbtn25.config(image=redimg)
    print(type(seatbtn25.cget("text")))
    print(seatbtn25.cget("text"))
def changecolor26():
    seatbtn26.config(image=redimg)
    print(type(seatbtn26.cget("text")))
    print(seatbtn26.cget("text"))
def changecolor27():
    seatbtn27.config(image=redimg)
    print(type(seatbtn27.cget("text")))
    print(seatbtn27.cget("text"))
def changecolor28():
    seatbtn28.config(image=redimg)
    print(type(seatbtn28.cget("text")))
    print(seatbtn28.cget("text"))
def changecolor29():
    seatbtn29.config(image=redimg)
    print(type(seatbtn29.cget("text")))
    print(seatbtn29.cget("text"))
def changecolor30():
    seatbtn30.config(image=redimg)
    print(type(seatbtn30.cget("text")))
    print(seatbtn30.cget("text"))
def changecolor31():
    seatbtn31.config(image=redimg)
    print(type(seatbtn31.cget("text")))
    print(seatbtn31.cget("text"))
def changecolor32():
    seatbtn32.config(image=redimg)
    print(type(seatbtn32.cget("text")))
    print(seatbtn32.cget("text"))
def changecolor33():
    seatbtn33.config(image=redimg)
    print(type(seatbtn33.cget("text")))
    print(seatbtn33.cget("text"))
def changecolor34():
    seatbtn34.config(image=redimg)
    print(type(seatbtn34.cget("text")))
    print(seatbtn34.cget("text"))
def changecolor35():
    seatbtn35.config(image=redimg)
    print(type(seatbtn35.cget("text")))
    print(seatbtn35.cget("text"))
def changecolor36():
    seatbtn36.config(image=redimg)
    print(type(seatbtn36.cget("text")))
    print(seatbtn36.cget("text"))
def changecolor37():
    seatbtn37.config(image=redimg)
    print(type(seatbtn37.cget("text")))
    print(seatbtn37.cget("text"))
def changecolor38():
    seatbtn38.config(image=redimg)
    print(type(seatbtn38.cget("text")))
    print(seatbtn38.cget("text"))
def changecolor39():
    seatbtn39.config(image=redimg)
    print(type(seatbtn39.cget("text")))
    print(seatbtn39.cget("text"))
def changecolor40():
    seatbtn40.config(image=redimg)
    print(type(seatbtn40.cget("text")))
    print(seatbtn40.cget("text"))
def changecolor41():
    seatbtn41.config(image=redimg)
    print(type(seatbtn41.cget("text")))
    print(seatbtn41.cget("text"))
def changecolor42():
    seatbtn42.config(image=redimg)
    print(type(seatbtn42.cget("text")))
    print(seatbtn42.cget("text"))
def changecolor43():
    seatbtn43.config(image=redimg)
    print(type(seatbtn43.cget("text")))
    print(seatbtn43.cget("text"))
def changecolor44():
    seatbtn44.config(image=redimg)
    print(type(seatbtn44.cget("text")))
    print(seatbtn44.cget("text"))
def changecolor45():
    seatbtn45.config(image=redimg)
    print(type(seatbtn45.cget("text")))
    print(seatbtn45.cget("text"))
def changecolor46():
    seatbtn46.config(image=redimg)
    print(type(seatbtn46.cget("text")))
    print(seatbtn46.cget("text"))
def changecolor47():
    seatbtn47.config(image=redimg)
    print(type(seatbtn47.cget("text")))
    print(seatbtn47.cget("text"))
def changecolor48():
    seatbtn48.config(image=redimg)
    print(type(seatbtn48.cget("text")))
    print(seatbtn48.cget("text"))
def changecolor49():
    seatbtn49.config(image=redimg)
    print(type(seatbtn49.cget("text")))
    print(seatbtn49.cget("text"))
def changecolor50():
    seatbtn50.config(image=redimg)
    print(type(seatbtn50.cget("text")))
    print(seatbtn50.cget("text"))
def changecolor51():
    seatbtn51.config(image=redimg)
    print(type(seatbtn51.cget("text")))
    print(seatbtn51.cget("text"))
def changecolor52():
    seatbtn52.config(image=redimg)
    print(type(seatbtn52.cget("text")))
    print(seatbtn52.cget("text"))
def changecolor53():
    seatbtn53.config(image=redimg)
    print(type(seatbtn53.cget("text")))
    print(seatbtn53.cget("text"))
def changecolor54():
    seatbtn54.config(image=redimg)
    print(type(seatbtn54.cget("text")))
    print(seatbtn54.cget("text"))
def changecolor55():
    seatbtn55.config(image=redimg)
    print(type(seatbtn55.cget("text")))
    print(seatbtn55.cget("text"))
def changecolor56():
    seatbtn56.config(image=redimg)
    print(type(seatbtn56.cget("text")))
    print(seatbtn56.cget("text"))
#Container
containerframe = LabelFrame(root, bg=blue)
#Header
headerframe = LabelFrame(containerframe, bg=blue)
brandframe = LabelFrame(headerframe, bd=0, bg=blue)
dateframe = LabelFrame(headerframe, bd=0, bg=blue)
trainbrandlabel = Label(brandframe, text='TRAIN MANAGEMENT SYSTEM', bg=blue, fg='white', font=large_font)
now = datetime.now()
day = datetime.today().strftime('%A')
dt_string = now.strftime(f"{day} %H:%M %d/%m/%Y")
trainbrandlabel2 = Label(dateframe, text=dt_string, bg=blue, fg='white', font=small_font)
#Display Header
brandframe.grid(row=0, column=0, ipadx=60)
dateframe.grid(row=0, column=1, ipadx=100)
trainbrandlabel.pack(pady=15)
trainbrandlabel2.pack(pady=15)
#Blank Frame 1
blankframe1 = LabelFrame(containerframe, bg=grey, bd=0)
#Menu Frame
menuframe = LabelFrame(containerframe, bd=0, bg=blue)
homebtn = Button(menuframe, text="Home", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white", command=homepage)
findticketbtn = Button(menuframe, text="Find Ticket", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white", command=findtrip)
reservebtn = Button(menuframe, text="Reservation Information", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
checkticketbtn = Button(menuframe, text="Check Ticket", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
regulationbtn = Button(menuframe, text="Regulations", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
guidesbtn = Button(menuframe, text="Guides", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
contactbtn = Button(menuframe, text="Contact", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
#Display Menu
homebtn.grid(row=0, column=0, ipadx=25)
findticketbtn.grid(row=0, column=1, ipadx=25)
reservebtn.grid(row=0, column=2, ipadx=25)
checkticketbtn.grid(row=0, column=3, ipadx=25)
regulationbtn.grid(row=0, column=4, ipadx=25)
guidesbtn.grid(row=0, column=5, ipadx=15)
contactbtn.grid(row=0, column=6, ipadx=15)
#START HOME PAGE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
homebodyframe = LabelFrame(containerframe)
#Blank Frame 2
homeblankframe2 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe2.pack(fill=X, ipady=17)
#Home Image Frame
homeimageframe = LabelFrame(homebodyframe, bd=0)
homeimageframe.pack(fill=X)
homeimage = ImageTk.PhotoImage(Image.open('images/homeimage.png').resize((750,200), Image.ANTIALIAS))
imagelabel = Label(homeimageframe, image=homeimage, bg='white', bd=0)
#Display Image
imagelabel.pack(fill=X)
#Look for Frame
lookforframe = LabelFrame(homebodyframe, bg=blue, bd=0)
wheretogoframe = LabelFrame(lookforframe, bg=blue, bd=0)
findtripenntryframe = LabelFrame(lookforframe, bg=blue, bd=0)
seetriplabelframe = LabelFrame(lookforframe, bg=blue, bd=0)
wheretogolabel = Label(wheretogoframe, text="Where do you want to go?", fg="white", bg=blue, font=medium_font)
findtripentry = Entry(findtripenntryframe, font=small_font)
findtripbtn = Button(findtripenntryframe, text="GO", fg='white', bg=weightedblue)
seetripbtn = Button(seetriplabelframe, text='SEE ALL TRIP', fg="white", bg=weightedblue, font=small_font)
nulllframe = LabelFrame(lookforframe, bg=blue, bd=0)
#Display Look for Frame
lookforframe.pack(fill=X)
wheretogoframe.grid(row=0, column=0, ipadx=80)
findtripenntryframe.grid(row=0, column=1)
seetriplabelframe.grid(row=0, column=2, ipadx=80)
nulllframe.grid(row=0, column=3, ipadx=0, ipady=25)
wheretogolabel.pack()
findtripentry.grid(row=0, column=0, ipadx=20, ipady=7)
findtripbtn.grid(row=0, column=1, ipady=5)
seetripbtn.pack()
#Blank Frame 3
homeblankframe3 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe3.pack(fill=X, ipady=17)
#Train Future
futureframe = LabelFrame(homebodyframe, bd=0)
tmplabel = Label(futureframe, text='Train Future', font=large_font)
#Display Future
futureframe.pack(fill=X, ipady=25)
tmplabel.pack(anchor=CENTER)
#Blank Frame 4
homeblankframe4 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe4.pack(fill=X, ipady=17)
#Footer Frame
footerframe = LabelFrame(containerframe, bg=lightblack, bd=0)
tmplabel2 = Label(footerframe, text='ON WORKING', bg=lightblack, fg='white', font=medium_font).pack()

#START FIND PAGE !!!!!!!!!!!!!!!!!!!!!!
findbodyframe = LabelFrame(containerframe, bd=0, bg=grey)
#Blank Frame 1
findblankframe1 = LabelFrame(findbodyframe, bg=grey, bd=0)
findblankframe1.pack(fill=X, ipady=5)
#Comprehension Part
findcomprehensionframe = LabelFrame(findbodyframe, bd=0, bg=blue)
findcomprehensionlabel = Label(findcomprehensionframe, text="Find Ticket", font=medium_font, bg=blue, fg="white")
findcomprehensionframe.pack(ipadx=25)
findcomprehensionlabel.pack()
#Blank Frame 2
findblankframe2 = LabelFrame(findbodyframe, bg=grey, bd=0)
findblankframe2.pack(fill=X, ipady=17)
#Find Form Frame
findformframe = LabelFrame(findbodyframe, background="white", bd=0, highlightthickness=3, highlightbackground = "black")
findformframe.pack(ipadx=60)
marginframe1 = LabelFrame(findformframe, bg='white', bd=0)
marginframe1.pack()
journeyinfolabel = Label(marginframe1, text='JOURNEY INFORMATION', font=medium_font, fg=blue, bg="white")
journeyinfolabel.grid(row=0, column=0, ipadx=200)
#Blank Frame 3 (Horizontal Line)
findblankframe3 = LabelFrame(findformframe, bg='white', highlightthickness=2, highlightbackground = "black")
findblankframe3.pack(fill=X)
#Starting Station
marginframe2 = LabelFrame(findformframe, bd=0, bg=lightedgrey)
marginframe2.pack()
startlabel = Label(marginframe2, text='Starting Station', font=small_font, fg=blue, bg=lightedgrey)
startlabel.grid(row=1, column=0, sticky=W, columnspan=2)
startentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
startentry.grid(row=2, column=0, ipadx=270, ipady=5, columnspan=2)
#Blank Frame 4
findblankframe4 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe4.grid(row=3, column=0, ipady=7, columnspan=2)
#Destination Station
destilabel = Label(marginframe2, text='Destination', font=small_font, fg=blue, bg=lightedgrey)
destilabel.grid(row=4, column=0, sticky=W, columnspan=2)
destientry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
destientry.grid(row=5, column=0, ipadx=270, ipady=5, columnspan=2)
#Blank Frame 5
findblankframe5 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe5.grid(row=6, column=0, ipady=7, columnspan=2)
#One-Doulbe Way selection
r1 = IntVar()
Radiobutton(marginframe2, text="One-way", font=small_font, fg=blue, variable=r1, value=1).grid(row=7, column=0)
Radiobutton(marginframe2, text='Round-trip', font=small_font, fg=blue, variable=r1, value=2).grid(row=7, column=1)
#Blank Frame 6
findblankframe6 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe6.grid(row=8, column=0, ipady=7, columnspan=2)
#Depart and Return Day
departlabel = Label(marginframe2, text='Departure Day', font=small_font, fg=blue, bg=lightedgrey)
departlabel.grid(row=9, column=0, sticky=W)
departentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
departentry.grid(row=10, column=0, ipadx=35, ipady=5, sticky=W)
returndaylabel = Label(marginframe2, text='Returning Day', font=small_font, fg=blue, bg=lightedgrey)
returndaylabel.grid(row=9, column=1, sticky=W)
returndayentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
returndayentry.grid(row=10, column=1, ipadx=35, ipady=5, sticky=W)
#Blank Frame 7
findblankframe7 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe7.grid(row=11, column=0, ipady=7, columnspan=2)
#Find Button
submitfindbtn = Button(marginframe2, text="FIND", font=medium_font, fg="white", bg=blue, command=findseat)
submitfindbtn.grid(row=12, ipadx=40, columnspan=2)

#START FIND SEAT PAGE !!!!!!!!!!!!!!!!!!!
findseatbodyframe = LabelFrame(containerframe, bd=0, bg=grey)
#Blank Frame 1
seatblankframe1 = LabelFrame(findseatbodyframe, bg=grey, bd=0)
seatblankframe1.pack(fill=X, ipady=35)
#Seat Background Frame
seatbgframe = LabelFrame(findseatbodyframe, bd=0, bg=grey)
seatbgframe.pack()
#Seat Holder Container Frame
seatcontainerframe = LabelFrame(seatbgframe, highlightthickness=2, highlightbackground = blue)
seatcontainerframe.grid(row=0, column=0)
#56 Seats (VERY LAZY THIS PART!!!!)
#Left-Mid-Right Part Frame
seatleftframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatmidframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatrightframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatleftframe.grid(row=0, column=0)
seatmidframe.grid(row=0, column=1)
seatrightframe.grid(row=0, column=2)
#Import Image
greenimg = ImageTk.PhotoImage(Image.open('images/green.png').resize((54, 41), Image.ANTIALIAS))
redimg = ImageTk.PhotoImage(Image.open('images/red.png').resize((54, 41), Image.ANTIALIAS))
barriel = ImageTk.PhotoImage(Image.open('images/barriel.png').resize((40, 90), Image.ANTIALIAS))
#Seat Left Display
seatbtn1 = Button(seatleftframe, image=greenimg, borderwidth=0, text=1, fg='white', font=medium_font, compound=CENTER, command=changecolor1)
seatbtn1.grid(row=0, column=0)
seatbtn2 = Button(seatleftframe, image=greenimg, borderwidth=0, text=2, fg='white', font=medium_font, compound=CENTER, command=changecolor2)
seatbtn2.grid(row=1, column=0)
seatbtn3 = Button(seatleftframe, image=greenimg, borderwidth=0, text=3, fg='white', font=medium_font, compound=CENTER, command=changecolor3)
seatbtn3.grid(row=2, column=0)
seatbtn4 = Button(seatleftframe, image=greenimg, borderwidth=0, text=4, fg='white', font=medium_font, compound=CENTER, command=changecolor4)
seatbtn4.grid(row=3, column=0)
seatbtn5 = Button(seatleftframe, image=greenimg, borderwidth=0, text=5, fg='white', font=medium_font, compound=CENTER, command=changecolor5)
seatbtn5.grid(row=3, column=1)
seatbtn6 = Button(seatleftframe, image=greenimg, borderwidth=0, text=6, fg='white', font=medium_font, compound=CENTER, command=changecolor6)
seatbtn6.grid(row=2, column=1)
seatbtn7 = Button(seatleftframe, image=greenimg, borderwidth=0, text=7, fg='white', font=medium_font, compound=CENTER, command=changecolor7)
seatbtn7.grid(row=1, column=1)
seatbtn8 = Button(seatleftframe, image=greenimg, borderwidth=0, text=8, fg='white', font=medium_font, compound=CENTER, command=changecolor8)
seatbtn8.grid(row=0, column=1)
seatbtn9 = Button(seatleftframe, image=greenimg, borderwidth=0, text=9, fg='white', font=medium_font, compound=CENTER, command=changecolor9)
seatbtn9.grid(row=0, column=2)
seatbtn10 = Button(seatleftframe, image=greenimg, borderwidth=0, text=10, fg='white', font=medium_font, compound=CENTER, command=changecolor10)
seatbtn10.grid(row=1, column=2)
seatbtn11 = Button(seatleftframe, image=greenimg, borderwidth=0, text=11, fg='white', font=medium_font, compound=CENTER, command=changecolor11)
seatbtn11.grid(row=2, column=2)
seatbtn12 = Button(seatleftframe, image=greenimg, borderwidth=0, text=12, fg='white', font=medium_font, compound=CENTER, command=changecolor12)
seatbtn12.grid(row=3, column=2)
seatbtn13 = Button(seatleftframe, image=greenimg, borderwidth=0, text=13, fg='white', font=medium_font, compound=CENTER, command=changecolor13)
seatbtn13.grid(row=3, column=3)
seatbtn14 = Button(seatleftframe, image=greenimg, borderwidth=0, text=14, fg='white', font=medium_font, compound=CENTER, command=changecolor14)
seatbtn14.grid(row=2, column=3)
seatbtn15 = Button(seatleftframe, image=greenimg, borderwidth=0, text=15, fg='white', font=medium_font, compound=CENTER, command=changecolor15)
seatbtn15.grid(row=1, column=3)
seatbtn16 = Button(seatleftframe, image=greenimg, borderwidth=0, text=16, fg='white', font=medium_font, compound=CENTER, command=changecolor16)
seatbtn16.grid(row=0, column=3)
seatbtn17 = Button(seatleftframe, image=greenimg, borderwidth=0, text=17, fg='white', font=medium_font, compound=CENTER, command=changecolor17)
seatbtn17.grid(row=0, column=4)
seatbtn18 = Button(seatleftframe, image=greenimg, borderwidth=0, text=18, fg='white', font=medium_font, compound=CENTER, command=changecolor18)
seatbtn18.grid(row=1, column=4)
seatbtn19 = Button(seatleftframe, image=greenimg, borderwidth=0, text=19, fg='white', font=medium_font, compound=CENTER, command=changecolor19)
seatbtn19.grid(row=2, column=4)
seatbtn20 = Button(seatleftframe, image=greenimg, borderwidth=0, text=20, fg='white', font=medium_font, compound=CENTER, command=changecolor20)
seatbtn20.grid(row=3, column=4)
seatbtn21 = Button(seatleftframe, image=greenimg, borderwidth=0, text=21, fg='white', font=medium_font, compound=CENTER, command=changecolor21)
seatbtn21.grid(row=3, column=5)
seatbtn22 = Button(seatleftframe, image=greenimg, borderwidth=0, text=22, fg='white', font=medium_font, compound=CENTER, command=changecolor22)
seatbtn22.grid(row=2, column=5)
seatbtn23 = Button(seatleftframe, image=greenimg, borderwidth=0, text=23, fg='white', font=medium_font, compound=CENTER, command=changecolor23)
seatbtn23.grid(row=1, column=5)
seatbtn24 = Button(seatleftframe, image=greenimg, borderwidth=0, text=24, fg='white', font=medium_font, compound=CENTER, command=changecolor24)
seatbtn24.grid(row=0, column=5)
seatbtn25 = Button(seatleftframe, image=greenimg, borderwidth=0, text=25, fg='white', font=medium_font, compound=CENTER, command=changecolor25)
seatbtn25.grid(row=0, column=6)
seatbtn26 = Button(seatleftframe, image=greenimg, borderwidth=0, text=26, fg='white', font=medium_font, compound=CENTER, command=changecolor26)
seatbtn26.grid(row=1, column=6)
seatbtn27 = Button(seatleftframe, image=greenimg, borderwidth=0, text=27, fg='white', font=medium_font, compound=CENTER, command=changecolor27)
seatbtn27.grid(row=2, column=6)
seatbtn28 = Button(seatleftframe, image=greenimg, borderwidth=0, text=28, fg='white', font=medium_font, compound=CENTER, command=changecolor28)
seatbtn28.grid(row=3, column=6)
#Seat Mid Display
barriel1label = Label(seatmidframe, image=barriel, bg=lightedgrey, bd=0)
barriel2label = Label(seatmidframe, image=barriel, bg=lightedgrey, bd=0)
barriel1label.pack()
barriel2label.pack()
#Seat Right Display
seatbtn29 = Button(seatrightframe, image=greenimg, borderwidth=0, text=29, fg='white', font=medium_font, compound=CENTER, command=changecolor29)
seatbtn29.grid(row=0, column=0)
seatbtn30 = Button(seatrightframe, image=greenimg, borderwidth=0, text=30, fg='white', font=medium_font, compound=CENTER, command=changecolor30)
seatbtn30.grid(row=1, column=0)
seatbtn31 = Button(seatrightframe, image=greenimg, borderwidth=0, text=31, fg='white', font=medium_font, compound=CENTER, command=changecolor31)
seatbtn31.grid(row=2, column=0)
seatbtn32 = Button(seatrightframe, image=greenimg, borderwidth=0, text=32, fg='white', font=medium_font, compound=CENTER, command=changecolor32)
seatbtn32.grid(row=3, column=0)
seatbtn33 = Button(seatrightframe, image=greenimg, borderwidth=0, text=33, fg='white', font=medium_font, compound=CENTER, command=changecolor33)
seatbtn33.grid(row=3, column=1)
seatbtn34 = Button(seatrightframe, image=greenimg, borderwidth=0, text=34, fg='white', font=medium_font, compound=CENTER, command=changecolor34)
seatbtn34.grid(row=2, column=1)
seatbtn35 = Button(seatrightframe, image=greenimg, borderwidth=0, text=35, fg='white', font=medium_font, compound=CENTER, command=changecolor35)
seatbtn35.grid(row=1, column=1)
seatbtn36 = Button(seatrightframe, image=greenimg, borderwidth=0, text=36, fg='white', font=medium_font, compound=CENTER, command=changecolor36)
seatbtn36.grid(row=0, column=1)
seatbtn37 = Button(seatrightframe, image=greenimg, borderwidth=0, text=37, fg='white', font=medium_font, compound=CENTER, command=changecolor37)
seatbtn37.grid(row=0, column=2)
seatbtn38 = Button(seatrightframe, image=greenimg, borderwidth=0, text=38, fg='white', font=medium_font, compound=CENTER, command=changecolor38)
seatbtn38.grid(row=1, column=2)
seatbtn39 = Button(seatrightframe, image=greenimg, borderwidth=0, text=39, fg='white', font=medium_font, compound=CENTER, command=changecolor39)
seatbtn39.grid(row=2, column=2)
seatbtn40 = Button(seatrightframe, image=greenimg, borderwidth=0, text=40, fg='white', font=medium_font, compound=CENTER, command=changecolor40)
seatbtn40.grid(row=3, column=2)
seatbtn41 = Button(seatrightframe, image=greenimg, borderwidth=0, text=41, fg='white', font=medium_font, compound=CENTER, command=changecolor41)
seatbtn41.grid(row=3, column=3)
seatbtn42 = Button(seatrightframe, image=greenimg, borderwidth=0, text=42, fg='white', font=medium_font, compound=CENTER, command=changecolor42)
seatbtn42.grid(row=2, column=3)
seatbtn43 = Button(seatrightframe, image=greenimg, borderwidth=0, text=43, fg='white', font=medium_font, compound=CENTER, command=changecolor43)
seatbtn43.grid(row=1, column=3)
seatbtn44 = Button(seatrightframe, image=greenimg, borderwidth=0, text=44, fg='white', font=medium_font, compound=CENTER, command=changecolor44)
seatbtn44.grid(row=0, column=3)
seatbtn45 = Button(seatrightframe, image=greenimg, borderwidth=0, text=45, fg='white', font=medium_font, compound=CENTER, command=changecolor45)
seatbtn45.grid(row=0, column=4)
seatbtn46 = Button(seatrightframe, image=greenimg, borderwidth=0, text=46, fg='white', font=medium_font, compound=CENTER, command=changecolor46)
seatbtn46.grid(row=1, column=4)
seatbtn47 = Button(seatrightframe, image=greenimg, borderwidth=0, text=47, fg='white', font=medium_font, compound=CENTER, command=changecolor47)
seatbtn47.grid(row=2, column=4)
seatbtn48 = Button(seatrightframe, image=greenimg, borderwidth=0, text=48, fg='white', font=medium_font, compound=CENTER, command=changecolor48)
seatbtn48.grid(row=3, column=4)
seatbtn49 = Button(seatrightframe, image=greenimg, borderwidth=0, text=49, fg='white', font=medium_font, compound=CENTER, command=changecolor49)
seatbtn49.grid(row=3, column=5)
seatbtn50 = Button(seatrightframe, image=greenimg, borderwidth=0, text=50, fg='white', font=medium_font, compound=CENTER, command=changecolor50)
seatbtn50.grid(row=2, column=5)
seatbtn51 = Button(seatrightframe, image=greenimg, borderwidth=0, text=51, fg='white', font=medium_font, compound=CENTER, command=changecolor51)
seatbtn51.grid(row=1, column=5)
seatbtn52 = Button(seatrightframe, image=greenimg, borderwidth=0, text=52, fg='white', font=medium_font, compound=CENTER, command=changecolor52)
seatbtn52.grid(row=0, column=5)
seatbtn53 = Button(seatrightframe, image=greenimg, borderwidth=0, text=53, fg='white', font=medium_font, compound=CENTER, command=changecolor53)
seatbtn53.grid(row=0, column=6)
seatbtn54 = Button(seatrightframe, image=greenimg, borderwidth=0, text=54, fg='white', font=medium_font, compound=CENTER, command=changecolor54)
seatbtn54.grid(row=1, column=6)
seatbtn55 = Button(seatrightframe, image=greenimg, borderwidth=0, text=55, fg='white', font=medium_font, compound=CENTER, command=changecolor55)
seatbtn55.grid(row=2, column=6)
seatbtn56 = Button(seatrightframe, image=greenimg, borderwidth=0, text=56, fg='white', font=medium_font, compound=CENTER, command=changecolor56)
seatbtn56.grid(row=3, column=6)
#Blank Frame 2
seatblankframe2 = LabelFrame(findseatbodyframe, bg=grey, bd=0)
seatblankframe2.pack(fill=X, ipady=15)
#Find Seat Submit Button
findseatbtn = Button(findseatbodyframe, text="Next", fg="white", bg=blue, font=medium_font, command=userinfo)
findseatbtn.pack(ipadx=40)
#User Info Page Frame !!!!!!!!!!!!!!!!!!
userinfobodyframe = LabelFrame(containerframe, bd = 0, bg=grey)
#Blank Frame 1
customerinfoblankframe1 = LabelFrame(userinfobodyframe, bg=grey, bd=0)
customerinfoblankframe1.pack(fill=X, ipady=25)
userholderframe = LabelFrame(userinfobodyframe, highlightthickness=2, highlightbackground = blue, bg='white')
userholderframe.pack()
#Customer Info(1st Page)
firstpageframe = LabelFrame(userholderframe, bd=0, bg='white')
firstpageframe.pack()
#Progress Bar
progress1img = ImageTk.PhotoImage(Image.open('images/customerinfobar.png').resize((800, 100), Image.ANTIALIAS))
progresslabel = Label(firstpageframe, image=progress1img, bg='white')
progresslabel.grid(row=0, column=0, columnspan=3)
#Sub head 1 label
subhead1img = ImageTk.PhotoImage(Image.open('images/customerinfolabel.png').resize((160, 60), Image.ANTIALIAS))
subhead1label = Label(firstpageframe, image=subhead1img, bg='white')
subhead1label.grid(row=1, column=0, sticky='W', pady=5)
#Left-Mid-Right UserInfo Frame
userinfoleftframe = LabelFrame(firstpageframe, bg='white', bd=0)
userinfoleftframe.grid(row=2, column=0, pady=10)
userinfomidframe = LabelFrame(firstpageframe, bg='white')
userinfomidframe.grid(row=2, column=1, ipady=10, pady=10)
userinforightframe = LabelFrame(firstpageframe, bg='white', bd=0)
userinforightframe.grid(row=2, column=2, pady=10)
#Component
fullnamelabel = Label(userinfoleftframe, text="Full Name", bg='white', font=small_font)
fullnamelabel.grid(row=0, column=0)
fullnameentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
fullnameentry.grid(row=0, column=1, ipady=5, pady=12)
emaillabel = Label(userinfoleftframe, text="Email", bg='white', font=small_font)
emaillabel.grid(row=1, column=0)
emailentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
emailentry.grid(row=1, column=1, ipady=5, pady=12)
phonenumberlabel = Label(userinfoleftframe, text="Phone Number", bg='white', font=small_font)
phonenumberlabel.grid(row=2, column=0)
phonenumberentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
phonenumberentry.grid(row=2, column=1, ipady=5, pady=12)
idpassportlabel = Label(userinforightframe, text="ID/Passport Number", bg='white', font=small_font)
idpassportlabel.grid(row=0, column=0)
idpassportentry = Entry(userinforightframe, font=small_font, highlightthickness=2, highlightbackground = blue)
idpassportentry.grid(row=0, column=1, ipady=5, pady=12)
emailconfirmlabel = Label(userinforightframe, text="Email Confirmation", bg='white', font=small_font)
emailconfirmlabel.grid(row=1, column=0)
emailconfirmentry = Entry(userinforightframe, font=small_font, highlightthickness=2, highlightbackground = blue)
emailconfirmentry.grid(row=1, column=1, ipady=5, pady=12)
userinfonextbtn = Button(firstpageframe, font=medium_font, text="Next", fg="white", bg=blue, command=payment)
userinfonextbtn.grid(row=3, column=0, columnspan=3, ipadx=15, pady=10)
#Payment Page(2nd Page)
secondpageframe = LabelFrame(userholderframe, bd=0, bg='white')
#Progress Bar
progress2img = ImageTk.PhotoImage(Image.open('images/paymentbar.png').resize((800, 100), Image.ANTIALIAS))
progress2label = Label(secondpageframe, image=progress2img, bg='white')
progress2label.grid(row=0, column=0)
#Sub head 2 label
subhead2img = ImageTk.PhotoImage(Image.open('images/paymentlabel.png').resize((160, 60), Image.ANTIALIAS))
subhead2label = Label(secondpageframe, image=subhead2img, bg='white')
subhead2label.grid(row=1, column=0, sticky='W', pady=5)
#Component page 2
r2 = IntVar()
Radiobutton(secondpageframe, text="Purchase offline(at gas station, postoffice)", font=medium_font, fg=blue, variable=r2, value=1, bg="white").grid(row=2, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by Naspas', font=medium_font, fg=blue, variable=r2, value=2, bg="white").grid(row=3, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by VNPay', font=medium_font, fg=blue, variable=r2, value=3, bg="white").grid(row=4, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by MOMO', font=medium_font, fg=blue, variable=r2, value=4, bg="white").grid(row=5, column=0, sticky='W', pady=5)
paymentnextbtn = Button(secondpageframe, font=medium_font, text="Next", fg="white", bg=blue, command=completed)
paymentnextbtn.grid(row=6, column=0, ipadx=15, pady=10)
#Completd Page(3rd Page)
thirdpageframe = LabelFrame(userholderframe, bd=0, bg='white')
#Progress Bar
progress3img = ImageTk.PhotoImage(Image.open('images/completedbar.png').resize((800, 100), Image.ANTIALIAS))
progress3label = Label(thirdpageframe, image=progress3img, bg='white')
progress3label.grid(row=0, column=0)
#Sub head 3 label
subhead3img = ImageTk.PhotoImage(Image.open('images/completedlabel.png').resize((160, 60), Image.ANTIALIAS))
subhead3label = Label(thirdpageframe, image=subhead3img, bg='white')
subhead3label.grid(row=1, column=0, sticky='W', pady=5)
#Component page 3
sucesspurchasedimg = ImageTk.PhotoImage(Image.open('images/successpurchased.png').resize((700, 70), Image.ANTIALIAS))
sucesspurchasedlabel = Label(thirdpageframe, image=sucesspurchasedimg, bg='white')
sucesspurchasedlabel.grid(row=2, column=0, pady=10)
endingpurchasesbtn = Button(thirdpageframe, font=medium_font, text="Back To Home Screen", fg="white", bg=blue, command=homepage)
endingpurchasesbtn.grid(row=3, column=0, pady=10)

#Display Fixed Frame
containerframe.pack(fill=BOTH, expand=YES)
headerframe.pack(fill=X, side=TOP)
blankframe1.pack(fill=X, ipady=17)
menuframe.pack(fill=X)
homebodyframe.pack(fill=X)
footerframe.pack(fill=X, side=BOTTOM)

root.mainloop()
