from tkinter import *
from tkinter import ttk
from PIL import ImageTk, Image
from datetime import datetime
root = Tk()
root.title('Good Job!')
root.geometry('1000x800') #wxh
root.maxsize(width=1000, height=800)
root.minsize(width=1000, height=700)
#Mystyle MyColor
lightedblue = '#%02x%02x%02x' % (67, 86, 145)
blue = '#%02x%02x%02x' % (42,42,123)
weightedblue = '#%02x%02x%02x' % (0,0,102)
green = '#%02x%02x%02x' % (48, 191, 81)
grey = '#%02x%02x%02x' % (208,208,208)
lightedgrey = '#%02x%02x%02x' % (235, 235, 235)
weightedgrey = '#%02x%02x%02x' % (126, 128, 135)
lightblack = '#%02x%02x%02x' % (42,42,42)
bluegrey = '#%02x%02x%02x' % (125, 137, 181)
large_font = ('Verdana',23)
med_large_font = ('Verdana',17)
medium_font = ('Verdana',15)
small_font = ('Verdana',11)
#function homebodyframe/findbodyframe/findseatbodyframe
def homepage():
    findbodyframe.pack_forget()
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack_forget()
    adminbodyframe.pack_forget()
    adminseatcontainerframe.grid_forget()
    firstpageframe.pack()
    secondpageframe.pack_forget()
    thirdpageframe.pack_forget()
    traininfodetailframe.pack_forget()
    homebodyframe.pack(fill=X)
def findtrip():
    homebodyframe.pack_forget()
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack_forget()
    adminbodyframe.pack_forget()
    adminseatcontainerframe.grid_forget()
    firstpageframe.pack()
    secondpageframe.pack_forget()
    thirdpageframe.pack_forget()
    traininfodetailframe.pack_forget()
    findbodyframe.pack(fill=X, ipady=50)
def findseat():
    homebodyframe.pack_forget()
    findbodyframe.pack_forget()
    adminbodyframe.pack_forget()
    traininfodetailframe.pack_forget()
    adminseatcontainerframe.grid_forget()
    findseatbodyframe.pack(fill=X, ipady=40)
def userinfo():
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack(fill=X, ipady=35)
def payment():
    firstpageframe.pack_forget()
    secondpageframe.pack()
def completed():
    secondpageframe.pack_forget()
    thirdpageframe.pack()
def admin():
    homebodyframe.pack_forget()
    findbodyframe.pack_forget()
    findseatbodyframe.pack_forget()
    userinfobodyframe.pack_forget()
    traininfodetailframe.pack_forget()
    adminseatcontainerframe.grid_forget()
    adminbodyframe.pack(fill=X, ipady=150)
def login():
    if usernameloginentry.get() == "admin" and passwordloginentry.get() == 'admin':
        centerframe.destroy()
        sidebarframe.pack(fill=BOTH, side=LEFT)
        dashboarddetailframe.pack(fill=BOTH, expand=YES, side=RIGHT)
    else:
        erropassLabel.config(text='Wrong Input, Try Again!', bg="red")
def dashboard():
    adminseatcontainerframe.grid_forget()
    traininfodetailframe.pack_forget()
    dashboardbtn.config(bg=weightedblue)
    traininfobtn.config(bg=lightedblue)
    aboutbtn.config(bg=lightedblue)
    dashboarddetailframe.pack(fill=BOTH, expand=YES, side=RIGHT)
    currenttrainframe.grid(row=0, column=0)
def adminfindseat():
    currenttrainframe.grid_forget()
    adminseatcontainerframe.grid(row=0, column=0, pady=200)
def traininfo():
    adminseatcontainerframe.grid_forget()
    dashboardbtn.config(bg=lightedblue)
    traininfobtn.config(bg=weightedblue)
    aboutbtn.config(bg=lightedblue)
    dashboarddetailframe.pack_forget()
    traininfodetailframe.pack(fill=BOTH, expand=YES, side=RIGHT)
    train()
def train():
    trainbtn.config(bg=weightedgrey)
    customerbtn.config(bg=bluegrey)
    customerfindingframe.pack_forget()
    trainfindingframe.pack(fill=BOTH, expand=YES)
result = [["SE1", "Route1", "3h", "4h", "56/56"], ["SE2", "Route2", "5h", "6h", "56/56"]]
def edit(index):
    edittrain = Tk()
    edittrain.geometry('450x280')  # wxh
    edittrain.resizable(False, False)
    print(index)
    editnamelabel = Label(edittrain, text="Name", font=medium_font)
    editnamelabel.grid(row=0, column=0, padx=5, pady=10)
    editnameentry = Entry(edittrain, font=medium_font)
    editnameentry.insert(0, result[index][0])
    editnameentry.grid(row=0, column=1, padx=5, pady=10)
    editroutelabel = Label(edittrain, text="Route", font=medium_font)
    editroutelabel.grid(row=1, column=0, padx=5, pady=10)
    editrouteentry = Entry(edittrain, font=medium_font)
    editrouteentry.insert(0, result[index][1])
    editrouteentry.grid(row=1, column=1, padx=5, pady=10)
    editdeptimelabel = Label(edittrain, text="Dep. Time", font=medium_font)
    editdeptimelabel.grid(row=2, column=0, padx=5, pady=10)
    editdeptimeentry = Entry(edittrain, font=medium_font)
    editdeptimeentry.insert(0, result[index][2])
    editdeptimeentry.grid(row=2, column=1, padx=5, pady=10)
    editarrtimelabel = Label(edittrain, text="Arr. Time", font=medium_font)
    editarrtimelabel.grid(row=3, column=0, padx=5, pady=10)
    editarrtimeentry = Entry(edittrain, font=medium_font)
    editarrtimeentry.insert(0, result[index][3])
    editarrtimeentry.grid(row=3, column=1, padx=5, pady=10)
    saveupdatebtn = Button(edittrain, text="Save", bg=green, fg='white', font=medium_font)
    saveupdatebtn.grid(row=4, columnspan=2, pady=10)

def listtrain():
    editbtn = []
    editbtn1 = Button(traintableframe, text="EDIT 1" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(0))
    editbtn2 = Button(traintableframe, text="EDIT 2" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(1))
    editbtn3 = Button(traintableframe, text="EDIT 3" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(2))
    editbtn4 = Button(traintableframe, text="EDIT 4" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(3))
    editbtn5 = Button(traintableframe, text="EDIT 5" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(4))
    editbtn6 = Button(traintableframe, text="EDIT 6" , bg=blue, fg='white', font=small_font,
                    command=lambda: edit(5))
    editbtn.append((editbtn1))
    editbtn.append((editbtn2))
    editbtn.append((editbtn3))
    editbtn.append((editbtn4))
    editbtn.append((editbtn5))
    editbtn.append((editbtn6))
    for index, x in enumerate(result):
        rowindex = index+1
        idtrain = str(x[0])
        num = 0
        editbtn[index].grid(row=rowindex, column=5)
        for y in x:
            lookup_label = Label(traintableframe, text=y, bg='white', font=medium_font)
            lookup_label.grid(row=rowindex, column=num)
            num += 1
resultcustomer = [["Quynh", "123", "quynh@gmail.com", "180.000", "SE1"], ["Quan", "2902", "quan@gmail.com", "250.000", "SE5"]]
def editcustomer(index):
    editcustomer = Tk()
    editcustomer.geometry('450x280')  # wxh
    editcustomer.resizable(False, False)
    print(index)
    editnamelabel = Label(editcustomer, text="Name", font=medium_font)
    editnamelabel.grid(row=0, column=0, padx=5, pady=10)
    editnameentry = Entry(editcustomer, font=medium_font)
    editnameentry.insert(0, resultcustomer[index][0])
    editnameentry.grid(row=0, column=1, padx=5, pady=10)
    editpassportlabel = Label(editcustomer, text="ID/Passport", font=medium_font)
    editpassportlabel.grid(row=1, column=0, padx=5, pady=10)
    editpassportentry = Entry(editcustomer, font=medium_font)
    editpassportentry.insert(0, resultcustomer[index][1])
    editpassportentry.grid(row=1, column=1, padx=5, pady=10)
    editcontactlabel = Label(editcustomer, text="Contact", font=medium_font)
    editcontactlabel.grid(row=2, column=0, padx=5, pady=10)
    editcontactentry = Entry(editcustomer, font=medium_font)
    editcontactentry.insert(0, resultcustomer[index][2])
    editcontactentry.grid(row=2, column=1, padx=5, pady=10)
    editpricelabel = Label(editcustomer, text="Price", font=medium_font)
    editpricelabel.grid(row=3, column=0, padx=5, pady=10)
    editpriceentry = Entry(editcustomer, font=medium_font)
    editpriceentry.insert(0, resultcustomer[index][3])
    editpriceentry.grid(row=3, column=1, padx=5, pady=10)
    edittrainnamelabel = Label(editcustomer, text="Train Name", font=medium_font)
    edittrainnamelabel.grid(row=3, column=0, padx=5, pady=10)
    edittrainnameentry = Entry(editcustomer, font=medium_font)
    edittrainnameentry.insert(0, resultcustomer[index][4])
    edittrainnameentry.grid(row=3, column=1, padx=5, pady=10)
    saveupdatebtn = Button(editcustomer, text="Save", bg=green, fg='white', font=medium_font)
    saveupdatebtn.grid(row=4, columnspan=2, pady=10)
def listcustomer():
    editbtn = []
    editbtn1 = Button(customertableframe, text="EDIT 1", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(0))
    editbtn2 = Button(customertableframe, text="EDIT 2", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(1))
    editbtn3 = Button(customertableframe, text="EDIT 3", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(2))
    editbtn4 = Button(customertableframe, text="EDIT 4", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(3))
    editbtn5 = Button(customertableframe, text="EDIT 5", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(4))
    editbtn6 = Button(customertableframe, text="EDIT 6", bg=blue, fg='white', font=small_font,
                      command=lambda: editcustomer(5))
    editbtn.append((editbtn1))
    editbtn.append((editbtn2))
    editbtn.append((editbtn3))
    editbtn.append((editbtn4))
    editbtn.append((editbtn5))
    editbtn.append((editbtn6))
    for index, x in enumerate(resultcustomer):
        rowindex = index + 1
        idtrain = str(x[0])
        num = 0
        editbtn[index].grid(row=rowindex, column=5)
        for y in x:
            lookup_label = Label(customertableframe, text=y, bg='white', font=medium_font)
            lookup_label.grid(row=rowindex, column=num)
            num += 1
def newtrain():
    #New Window for Add Train
    trainwindow = Tk()
    trainwindow.geometry('450x250')  # wxh
    trainwindow.resizable(False, False)
    # Create a Label
    title_label = Label(trainwindow, text="Add Train", font=med_large_font)
    title_label.grid(row=0, column=0, columnspan=2, pady=10)

    # Create Main Form To Ente Data
    newnamelabel = Label(trainwindow, text="Name", font=medium_font)
    newnamelabel.grid(row=1, column=0, sticky=W, padx=10)

    newroutelabel = Label(trainwindow, text="Route", font=medium_font)
    newroutelabel.grid(row=2, column=0, sticky=W, padx=10)
    newdeparttimelabel = Label(trainwindow, text="Depature Time", font=medium_font)
    newdeparttimelabel.grid(row=3, column=0, sticky=W, padx=10)
    # Create Entry Boxes
    newnameentry = Entry(trainwindow, bd=0, highlightthickness=2, highlightbackground=blue, font=medium_font)
    newnameentry.grid(row=1, column=1, padx=10)
    n = StringVar()
    newroutecombobox = ttk.Combobox(trainwindow,  width = 18, font=medium_font, textvariable=n)
    newroutecombobox['values'] = (' SE1',
                              ' SE2',
                              ' SE3',
                              ' SE4',
                              ' SE5',
    )
    newroutecombobox.current(0)
    newroutecombobox.grid(row=2, column=1, pady=5, padx=1)
    newdeparttimeentry = Entry(trainwindow, bd=0, highlightthickness=2, highlightbackground = blue, font=medium_font)
    newdeparttimeentry.grid(row=3, column=1, pady=5, padx=10)

    # Create Buttons
    addcustomerbutton = Button(trainwindow, text="Add Customer To Database", font=small_font, width=15, bg=green, bd=2, fg="white")
    addcustomerbutton.grid(row=14, column=0, padx=10, pady=10, columnspan=2)
def customer():
    trainbtn.config(bg=bluegrey)
    customerbtn.config(bg=weightedgrey)
    trainfindingframe.pack_forget()
    customerfindingframe.pack(fill=BOTH, expand=YES)
def about():
    adminseatcontainerframe.grid_forget()
    dashboardbtn.config(bg=lightedblue)
    traininfobtn.config(bg=lightedblue)
    aboutbtn.config(bg=weightedblue)
    dashboarddetailframe.pack_forget()
seatlist = []
seated = [5, 12, 50]
def btnavailabel(seated):
    for i in seated:
        seatlist[i-1].config(image=redimg)
def changecolor1():
    seatbtn1.config(image=redimg)
    print(type(seatbtn1.cget("text")))
    print(seatbtn1.cget("text"))
def changecolor2():
    seatbtn2.config(image=redimg)
    print(type(seatbtn2.cget("text")))
    print(seatbtn2.cget("text"))
def changecolor3():
    seatbtn3.config(image=redimg)
    print(type(seatbtn3.cget("text")))
    print(seatbtn3.cget("text"))
def changecolor4():
    seatbtn4.config(image=redimg)
    print(type(seatbtn4.cget("text")))
    print(seatbtn4.cget("text"))
def changecolor5():
    seatbtn5.config(image=redimg)
    print(type(seatbtn5.cget("text")))
    print(seatbtn5.cget("text"))
def changecolor6():
    seatbtn6.config(image=redimg)
    print(type(seatbtn6.cget("text")))
    print(seatbtn6.cget("text"))
def changecolor7():
    seatbtn7.config(image=redimg)
    print(type(seatbtn7.cget("text")))
    print(seatbtn7.cget("text"))
def changecolor8():
    seatbtn8.config(image=redimg)
    print(type(seatbtn8.cget("text")))
    print(seatbtn8.cget("text"))
def changecolor9():
    seatbtn9.config(image=redimg)
    print(type(seatbtn9.cget("text")))
    print(seatbtn9.cget("text"))
def changecolor10():
    seatbtn10.config(image=redimg)
    print(type(seatbtn10.cget("text")))
    print(seatbtn10.cget("text"))
def changecolor11():
    seatbtn11.config(image=redimg)
    print(type(seatbtn11.cget("text")))
    print(seatbtn11.cget("text"))
def changecolor12():
    seatbtn12.config(image=redimg)
    print(type(seatbtn12.cget("text")))
    print(seatbtn12.cget("text"))
def changecolor13():
    seatbtn13.config(image=redimg)
    print(type(seatbtn13.cget("text")))
    print(seatbtn13.cget("text"))
def changecolor14():
    seatbtn14.config(image=redimg)
    print(type(seatbtn14.cget("text")))
    print(seatbtn14.cget("text"))
def changecolor15():
    seatbtn15.config(image=redimg)
    print(type(seatbtn15.cget("text")))
    print(seatbtn15.cget("text"))
def changecolor16():
    seatbtn16.config(image=redimg)
    print(type(seatbtn16.cget("text")))
    print(seatbtn16.cget("text"))
def changecolor17():
    seatbtn17.config(image=redimg)
    print(type(seatbtn17.cget("text")))
    print(seatbtn17.cget("text"))
def changecolor18():
    seatbtn18.config(image=redimg)
    print(type(seatbtn18.cget("text")))
    print(seatbtn18.cget("text"))
def changecolor19():
    seatbtn19.config(image=redimg)
    print(type(seatbtn19.cget("text")))
    print(seatbtn19.cget("text"))
def changecolor20():
    seatbtn20.config(image=redimg)
    print(type(seatbtn20.cget("text")))
    print(seatbtn20.cget("text"))
def changecolor21():
    seatbtn21.config(image=redimg)
    print(type(seatbtn21.cget("text")))
    print(seatbtn21.cget("text"))
def changecolor22():
    seatbtn22.config(image=redimg)
    print(type(seatbtn22.cget("text")))
    print(seatbtn22.cget("text"))
def changecolor23():
    seatbtn23.config(image=redimg)
    print(type(seatbtn23.cget("text")))
    print(seatbtn23.cget("text"))
def changecolor24():
    seatbtn24.config(image=redimg)
    print(type(seatbtn24.cget("text")))
    print(seatbtn24.cget("text"))
def changecolor25():
    seatbtn25.config(image=redimg)
    print(type(seatbtn25.cget("text")))
    print(seatbtn25.cget("text"))
def changecolor26():
    seatbtn26.config(image=redimg)
    print(type(seatbtn26.cget("text")))
    print(seatbtn26.cget("text"))
def changecolor27():
    seatbtn27.config(image=redimg)
    print(type(seatbtn27.cget("text")))
    print(seatbtn27.cget("text"))
def changecolor28():
    seatbtn28.config(image=redimg)
    print(type(seatbtn28.cget("text")))
    print(seatbtn28.cget("text"))
def changecolor29():
    seatbtn29.config(image=redimg)
    print(type(seatbtn29.cget("text")))
    print(seatbtn29.cget("text"))
def changecolor30():
    seatbtn30.config(image=redimg)
    print(type(seatbtn30.cget("text")))
    print(seatbtn30.cget("text"))
def changecolor31():
    seatbtn31.config(image=redimg)
    print(type(seatbtn31.cget("text")))
    print(seatbtn31.cget("text"))
def changecolor32():
    seatbtn32.config(image=redimg)
    print(type(seatbtn32.cget("text")))
    print(seatbtn32.cget("text"))
def changecolor33():
    seatbtn33.config(image=redimg)
    print(type(seatbtn33.cget("text")))
    print(seatbtn33.cget("text"))
def changecolor34():
    seatbtn34.config(image=redimg)
    print(type(seatbtn34.cget("text")))
    print(seatbtn34.cget("text"))
def changecolor35():
    seatbtn35.config(image=redimg)
    print(type(seatbtn35.cget("text")))
    print(seatbtn35.cget("text"))
def changecolor36():
    seatbtn36.config(image=redimg)
    print(type(seatbtn36.cget("text")))
    print(seatbtn36.cget("text"))
def changecolor37():
    seatbtn37.config(image=redimg)
    print(type(seatbtn37.cget("text")))
    print(seatbtn37.cget("text"))
def changecolor38():
    seatbtn38.config(image=redimg)
    print(type(seatbtn38.cget("text")))
    print(seatbtn38.cget("text"))
def changecolor39():
    seatbtn39.config(image=redimg)
    print(type(seatbtn39.cget("text")))
    print(seatbtn39.cget("text"))
def changecolor40():
    seatbtn40.config(image=redimg)
    print(type(seatbtn40.cget("text")))
    print(seatbtn40.cget("text"))
def changecolor41():
    seatbtn41.config(image=redimg)
    print(type(seatbtn41.cget("text")))
    print(seatbtn41.cget("text"))
def changecolor42():
    seatbtn42.config(image=redimg)
    print(type(seatbtn42.cget("text")))
    print(seatbtn42.cget("text"))
def changecolor43():
    seatbtn43.config(image=redimg)
    print(type(seatbtn43.cget("text")))
    print(seatbtn43.cget("text"))
def changecolor44():
    seatbtn44.config(image=redimg)
    print(type(seatbtn44.cget("text")))
    print(seatbtn44.cget("text"))
def changecolor45():
    seatbtn45.config(image=redimg)
    print(type(seatbtn45.cget("text")))
    print(seatbtn45.cget("text"))
def changecolor46():
    seatbtn46.config(image=redimg)
    print(type(seatbtn46.cget("text")))
    print(seatbtn46.cget("text"))
def changecolor47():
    seatbtn47.config(image=redimg)
    print(type(seatbtn47.cget("text")))
    print(seatbtn47.cget("text"))
def changecolor48():
    seatbtn48.config(image=redimg)
    print(type(seatbtn48.cget("text")))
    print(seatbtn48.cget("text"))
def changecolor49():
    seatbtn49.config(image=redimg)
    print(type(seatbtn49.cget("text")))
    print(seatbtn49.cget("text"))
def changecolor50():
    seatbtn50.config(image=redimg)
    print(type(seatbtn50.cget("text")))
    print(seatbtn50.cget("text"))
def changecolor51():
    seatbtn51.config(image=redimg)
    print(type(seatbtn51.cget("text")))
    print(seatbtn51.cget("text"))
def changecolor52():
    seatbtn52.config(image=redimg)
    print(type(seatbtn52.cget("text")))
    print(seatbtn52.cget("text"))
def changecolor53():
    seatbtn53.config(image=redimg)
    print(type(seatbtn53.cget("text")))
    print(seatbtn53.cget("text"))
def changecolor54():
    seatbtn54.config(image=redimg)
    print(type(seatbtn54.cget("text")))
    print(seatbtn54.cget("text"))
def changecolor55():
    seatbtn55.config(image=redimg)
    print(type(seatbtn55.cget("text")))
    print(seatbtn55.cget("text"))
def changecolor56():
    seatbtn56.config(image=redimg)
    print(type(seatbtn56.cget("text")))
    print(seatbtn56.cget("text"))
adminseatlist = []
seated1=[1,2,3]
def adminbtnavailabel(seated1):
    for i in seated1:
        adminseatlist[i-1].config(image=redimg)
#Container
containerframe = LabelFrame(root, bg=blue)
#Header
headerframe = LabelFrame(containerframe, bg=blue)
brandframe = LabelFrame(headerframe, bd=0, bg=blue)
dateframe = LabelFrame(headerframe, bd=0, bg=blue)
trainbrandlabel = Label(brandframe, text='TRAIN MANAGEMENT SYSTEM', bg=blue, fg='white', font=large_font)
now = datetime.now()
day = datetime.today().strftime('%A')
dt_string = now.strftime(f"{day} %H:%M %d/%m/%Y")
trainbrandlabel2 = Label(dateframe, text=dt_string, bg=blue, fg='white', font=small_font)
#Display Header
brandframe.grid(row=0, column=0, ipadx=60)
dateframe.grid(row=0, column=1, ipadx=100)
trainbrandlabel.pack(pady=15)
trainbrandlabel2.pack(pady=15)
#Blank Frame 1
blankframe1 = LabelFrame(containerframe, bg=grey, bd=0)
#Menu Frame
menuframe = LabelFrame(containerframe, bd=0, bg=blue)
homebtn = Button(menuframe, text="Home", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white", command=homepage)
findticketbtn = Button(menuframe, text="Find Ticket", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white", command=findtrip)
reservebtn = Button(menuframe, text="Reservation Information", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
checkticketbtn = Button(menuframe, text="Check Ticket", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
regulationbtn = Button(menuframe, text="Regulations", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
guidesbtn = Button(menuframe, text="Guides", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white")
adminbtn = Button(menuframe, text="Admin", fg='white', font=small_font, bg=blue, bd=2, highlightbackground = "white", command=admin)
#Display Menu
homebtn.grid(row=0, column=0, ipadx=25)
findticketbtn.grid(row=0, column=1, ipadx=25)
reservebtn.grid(row=0, column=2, ipadx=25)
checkticketbtn.grid(row=0, column=3, ipadx=25)
regulationbtn.grid(row=0, column=4, ipadx=25)
guidesbtn.grid(row=0, column=5, ipadx=15)
adminbtn.grid(row=0, column=6, ipadx=25)
#START HOME PAGE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
homebodyframe = LabelFrame(containerframe)
#Blank Frame 2
homeblankframe2 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe2.pack(fill=X, ipady=17)
#Home Image Frame
homeimageframe = LabelFrame(homebodyframe, bd=0)
homeimageframe.pack(fill=X)
homeimage = ImageTk.PhotoImage(Image.open('images/homeimage.png').resize((750,200), Image.ANTIALIAS))
imagelabel = Label(homeimageframe, image=homeimage, bg='white', bd=0)
#Display Image
imagelabel.pack(fill=X)
#Look for Frame
lookforframe = LabelFrame(homebodyframe, bg=blue, bd=0)
wheretogoframe = LabelFrame(lookforframe, bg=blue, bd=0)
findtripenntryframe = LabelFrame(lookforframe, bg=blue, bd=0)
seetriplabelframe = LabelFrame(lookforframe, bg=blue, bd=0)
wheretogolabel = Label(wheretogoframe, text="Where do you want to go?", fg="white", bg=blue, font=medium_font)
findtripentry = Entry(findtripenntryframe, font=small_font)
findtripbtn = Button(findtripenntryframe, text="GO", fg='white', bg=weightedblue)
seetripbtn = Button(seetriplabelframe, text='SEE ALL TRIP', fg="white", bg=weightedblue, font=small_font)
nulllframe = LabelFrame(lookforframe, bg=blue, bd=0)
#Display Look for Frame
lookforframe.pack(fill=X)
wheretogoframe.grid(row=0, column=0, ipadx=80)
findtripenntryframe.grid(row=0, column=1)
seetriplabelframe.grid(row=0, column=2, ipadx=80)
nulllframe.grid(row=0, column=3, ipadx=0, ipady=25)
wheretogolabel.pack()
findtripentry.grid(row=0, column=0, ipadx=20, ipady=7)
findtripbtn.grid(row=0, column=1, ipady=5)
seetripbtn.pack()
#Blank Frame 3
homeblankframe3 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe3.pack(fill=X, ipady=17)
#Train Future
futureframe = LabelFrame(homebodyframe, bd=0)
tmplabel = Label(futureframe, text='Train Future', font=large_font)
#Display Future
futureframe.pack(fill=X, ipady=25)
tmplabel.pack(anchor=CENTER)
#Blank Frame 4
homeblankframe4 = LabelFrame(homebodyframe, bg=grey, bd=0)
homeblankframe4.pack(fill=X, ipady=17)
#Footer Frame
footerframe = LabelFrame(containerframe, bg=lightblack, bd=0)
tmplabel2 = Label(footerframe, text='ON WORKING', bg=lightblack, fg='white', font=medium_font).pack()

findbodyframe = LabelFrame(containerframe, bd=0, bg=grey)
#Blank Frame 1
findblankframe1 = LabelFrame(findbodyframe, bg=grey, bd=0)
findblankframe1.pack(fill=X, ipady=5)
#Comprehension Part
findcomprehensionframe = LabelFrame(findbodyframe, bd=0, bg=blue)
findcomprehensionlabel = Label(findcomprehensionframe, text="Find Ticket", font=medium_font, bg=blue, fg="white")
findcomprehensionframe.pack(ipadx=25)
findcomprehensionlabel.pack()
#Blank Frame 2
findblankframe2 = LabelFrame(findbodyframe, bg=grey, bd=0)
findblankframe2.pack(fill=X, ipady=17)
#Find Form Frame
findformframe = LabelFrame(findbodyframe, background="white", bd=0, highlightthickness=3, highlightbackground = "black")
findformframe.pack(ipadx=60)
marginframe1 = LabelFrame(findformframe, bg='white', bd=0)
marginframe1.pack()
journeyinfolabel = Label(marginframe1, text='JOURNEY INFORMATION', font=medium_font, fg=blue, bg="white")
journeyinfolabel.grid(row=0, column=0, ipadx=200)
#Blank Frame 3 (Horizontal Line)
findblankframe3 = LabelFrame(findformframe, bg='white', highlightthickness=2, highlightbackground = "black")
findblankframe3.pack(fill=X)
#Starting Station
marginframe2 = LabelFrame(findformframe, bd=0, bg=lightedgrey)
marginframe2.pack()
startlabel = Label(marginframe2, text='Starting Station', font=small_font, fg=blue, bg=lightedgrey)
startlabel.grid(row=1, column=0, sticky=W, columnspan=2)
startentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
startentry.grid(row=2, column=0, ipadx=270, ipady=5, columnspan=2)
#Blank Frame 4
findblankframe4 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe4.grid(row=3, column=0, ipady=7, columnspan=2)
#Destination Station
destilabel = Label(marginframe2, text='Destination', font=small_font, fg=blue, bg=lightedgrey)
destilabel.grid(row=4, column=0, sticky=W, columnspan=2)
destientry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
destientry.grid(row=5, column=0, ipadx=270, ipady=5, columnspan=2)
#Blank Frame 5
findblankframe5 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe5.grid(row=6, column=0, ipady=7, columnspan=2)
#One-Doulbe Way selection
r1 = IntVar()
Radiobutton(marginframe2, text="One-way", font=small_font, fg=blue, variable=r1, value=1).grid(row=7, column=0)
Radiobutton(marginframe2, text='Round-trip', font=small_font, fg=blue, variable=r1, value=2).grid(row=7, column=1)
#Blank Frame 6
findblankframe6 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe6.grid(row=8, column=0, ipady=7, columnspan=2)
#Depart and Return Day
departlabel = Label(marginframe2, text='Departure Day', font=small_font, fg=blue, bg=lightedgrey)
departlabel.grid(row=9, column=0, sticky=W)
departentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
departentry.grid(row=10, column=0, ipadx=35, ipady=5, sticky=W)
returndaylabel = Label(marginframe2, text='Returning Day', font=small_font, fg=blue, bg=lightedgrey)
returndaylabel.grid(row=9, column=1, sticky=W)
returndayentry = Entry(marginframe2, highlightthickness=1, highlightbackground = blue, font=small_font)
returndayentry.grid(row=10, column=1, ipadx=35, ipady=5, sticky=W)
#Blank Frame 7
findblankframe7 = LabelFrame(marginframe2, bg=lightedgrey, bd=0)
findblankframe7.grid(row=11, column=0, ipady=7, columnspan=2)
#Find Button
submitfindbtn = Button(marginframe2, text="FIND", font=medium_font, fg="white", bg=blue, command=findseat)
submitfindbtn.grid(row=12, ipadx=40, columnspan=2)

#START FIND SEAT PAGE !!!!!!!!!!!!!!!!!!!
findseatbodyframe = LabelFrame(containerframe, bd=0, bg=grey)
#Blank Frame 1
seatblankframe1 = LabelFrame(findseatbodyframe, bg=grey, bd=0)
seatblankframe1.pack(fill=X, ipady=35)
#Seat Background Frame
seatbgframe = LabelFrame(findseatbodyframe, bd=0, bg=grey)
seatbgframe.pack()
#Seat Holder Container Frame
seatcontainerframe = LabelFrame(seatbgframe, highlightthickness=2, highlightbackground = blue)
seatcontainerframe.grid(row=0, column=0)
#56 Seats (VERY LAZY THIS PART!!!!)
#Left-Mid-Right Part Frame
seatleftframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatmidframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatrightframe = LabelFrame(seatcontainerframe, bd=0, bg=lightedgrey)
seatleftframe.grid(row=0, column=0)
seatmidframe.grid(row=0, column=1)
seatrightframe.grid(row=0, column=2)
#Import Image
greenimg = ImageTk.PhotoImage(Image.open('images/green.png').resize((54, 41), Image.ANTIALIAS))
redimg = ImageTk.PhotoImage(Image.open('images/red.png').resize((54, 41), Image.ANTIALIAS))
barriel = ImageTk.PhotoImage(Image.open('images/barriel.png').resize((40, 90), Image.ANTIALIAS))
#Seat Left Display
seatbtn1 = Button(seatleftframe, image=greenimg, borderwidth=0, text=1, fg='white', font=medium_font, compound=CENTER, command=changecolor1)
seatlist.append(seatbtn1)
seatbtn2 = Button(seatleftframe, image=greenimg, borderwidth=0, text=2, fg='white', font=medium_font, compound=CENTER, command=changecolor2)
seatlist.append(seatbtn2)
seatbtn3 = Button(seatleftframe, image=greenimg, borderwidth=0, text=3, fg='white', font=medium_font, compound=CENTER, command=changecolor3)
seatlist.append(seatbtn3)
seatbtn4 = Button(seatleftframe, image=greenimg, borderwidth=0, text=4, fg='white', font=medium_font, compound=CENTER, command=changecolor4)
seatlist.append(seatbtn4)
seatbtn5 = Button(seatleftframe, image=greenimg, borderwidth=0, text=5, fg='white', font=medium_font, compound=CENTER, command=changecolor5)
seatlist.append(seatbtn5)
seatbtn6 = Button(seatleftframe, image=greenimg, borderwidth=0, text=6, fg='white', font=medium_font, compound=CENTER, command=changecolor6)
seatlist.append(seatbtn6)
seatbtn7 = Button(seatleftframe, image=greenimg, borderwidth=0, text=7, fg='white', font=medium_font, compound=CENTER, command=changecolor7)
seatlist.append(seatbtn7)
seatbtn8 = Button(seatleftframe, image=greenimg, borderwidth=0, text=8, fg='white', font=medium_font, compound=CENTER, command=changecolor8)
seatlist.append(seatbtn8)
seatbtn9 = Button(seatleftframe, image=greenimg, borderwidth=0, text=9, fg='white', font=medium_font, compound=CENTER, command=changecolor9)
seatlist.append(seatbtn9)
seatbtn10 = Button(seatleftframe, image=greenimg, borderwidth=0, text=10, fg='white', font=medium_font, compound=CENTER, command=changecolor10)
seatlist.append(seatbtn10)
seatbtn11 = Button(seatleftframe, image=greenimg, borderwidth=0, text=11, fg='white', font=medium_font, compound=CENTER, command=changecolor11)
seatlist.append(seatbtn11)
seatbtn12 = Button(seatleftframe, image=greenimg, borderwidth=0, text=12, fg='white', font=medium_font, compound=CENTER, command=changecolor12)
seatlist.append(seatbtn12)
seatbtn13 = Button(seatleftframe, image=greenimg, borderwidth=0, text=13, fg='white', font=medium_font, compound=CENTER, command=changecolor13)
seatlist.append(seatbtn13)
seatbtn14 = Button(seatleftframe, image=greenimg, borderwidth=0, text=14, fg='white', font=medium_font, compound=CENTER, command=changecolor14)
seatlist.append(seatbtn14)
seatbtn15 = Button(seatleftframe, image=greenimg, borderwidth=0, text=15, fg='white', font=medium_font, compound=CENTER, command=changecolor15)
seatlist.append(seatbtn15)
seatbtn16 = Button(seatleftframe, image=greenimg, borderwidth=0, text=16, fg='white', font=medium_font, compound=CENTER, command=changecolor16)
seatlist.append(seatbtn16)
seatbtn17 = Button(seatleftframe, image=greenimg, borderwidth=0, text=17, fg='white', font=medium_font, compound=CENTER, command=changecolor17)
seatlist.append(seatbtn17)
seatbtn18 = Button(seatleftframe, image=greenimg, borderwidth=0, text=18, fg='white', font=medium_font, compound=CENTER, command=changecolor18)
seatlist.append(seatbtn18)
seatbtn19 = Button(seatleftframe, image=greenimg, borderwidth=0, text=19, fg='white', font=medium_font, compound=CENTER, command=changecolor19)
seatlist.append(seatbtn19)
seatbtn20 = Button(seatleftframe, image=greenimg, borderwidth=0, text=20, fg='white', font=medium_font, compound=CENTER, command=changecolor20)
seatlist.append(seatbtn20)
seatbtn21 = Button(seatleftframe, image=greenimg, borderwidth=0, text=21, fg='white', font=medium_font, compound=CENTER, command=changecolor21)
seatlist.append(seatbtn21)
seatbtn22 = Button(seatleftframe, image=greenimg, borderwidth=0, text=22, fg='white', font=medium_font, compound=CENTER, command=changecolor22)
seatlist.append(seatbtn22)
seatbtn23 = Button(seatleftframe, image=greenimg, borderwidth=0, text=23, fg='white', font=medium_font, compound=CENTER, command=changecolor23)
seatlist.append(seatbtn23)
seatbtn24 = Button(seatleftframe, image=greenimg, borderwidth=0, text=24, fg='white', font=medium_font, compound=CENTER, command=changecolor24)
seatlist.append(seatbtn24)
seatbtn25 = Button(seatleftframe, image=greenimg, borderwidth=0, text=25, fg='white', font=medium_font, compound=CENTER, command=changecolor25)
seatlist.append(seatbtn25)
seatbtn26 = Button(seatleftframe, image=greenimg, borderwidth=0, text=26, fg='white', font=medium_font, compound=CENTER, command=changecolor26)
seatlist.append(seatbtn26)
seatbtn27 = Button(seatleftframe, image=greenimg, borderwidth=0, text=27, fg='white', font=medium_font, compound=CENTER, command=changecolor27)
seatbtn27.grid(row=2, column=6)
seatlist.append(seatbtn27)
seatbtn28 = Button(seatleftframe, image=greenimg, borderwidth=0, text=28, fg='white', font=medium_font, compound=CENTER, command=changecolor28)
seatbtn28.grid(row=3, column=6)
seatlist.append(seatbtn28)
#Seat Mid Display
barriel1label = Label(seatmidframe, image=barriel, bg=lightedgrey, bd=0)
barriel2label = Label(seatmidframe, image=barriel, bg=lightedgrey, bd=0)
barriel1label.pack()
barriel2label.pack()
#Seat Right Display
seatbtn29 = Button(seatrightframe, image=greenimg, borderwidth=0, text=29, fg='white', font=medium_font, compound=CENTER, command=changecolor29)
seatlist.append(seatbtn29)
seatbtn30 = Button(seatrightframe, image=greenimg, borderwidth=0, text=30, fg='white', font=medium_font, compound=CENTER, command=changecolor30)
seatlist.append(seatbtn30)
seatbtn31 = Button(seatrightframe, image=greenimg, borderwidth=0, text=31, fg='white', font=medium_font, compound=CENTER, command=changecolor31)
seatlist.append(seatbtn31)
seatbtn32 = Button(seatrightframe, image=greenimg, borderwidth=0, text=32, fg='white', font=medium_font, compound=CENTER, command=changecolor32)
seatlist.append(seatbtn32)
seatbtn33 = Button(seatrightframe, image=greenimg, borderwidth=0, text=33, fg='white', font=medium_font, compound=CENTER, command=changecolor33)
seatlist.append(seatbtn33)
seatbtn34 = Button(seatrightframe, image=greenimg, borderwidth=0, text=34, fg='white', font=medium_font, compound=CENTER, command=changecolor34)
seatlist.append(seatbtn34)
seatbtn35 = Button(seatrightframe, image=greenimg, borderwidth=0, text=35, fg='white', font=medium_font, compound=CENTER, command=changecolor35)
seatlist.append(seatbtn35)
seatbtn36 = Button(seatrightframe, image=greenimg, borderwidth=0, text=36, fg='white', font=medium_font, compound=CENTER, command=changecolor36)
seatlist.append(seatbtn36)
seatbtn37 = Button(seatrightframe, image=greenimg, borderwidth=0, text=37, fg='white', font=medium_font, compound=CENTER, command=changecolor37)
seatlist.append(seatbtn37)
seatbtn38 = Button(seatrightframe, image=greenimg, borderwidth=0, text=38, fg='white', font=medium_font, compound=CENTER, command=changecolor38)
seatlist.append(seatbtn38)
seatbtn39 = Button(seatrightframe, image=greenimg, borderwidth=0, text=39, fg='white', font=medium_font, compound=CENTER, command=changecolor39)
seatlist.append(seatbtn39)
seatbtn40 = Button(seatrightframe, image=greenimg, borderwidth=0, text=40, fg='white', font=medium_font, compound=CENTER, command=changecolor40)
seatlist.append(seatbtn40)
seatbtn41 = Button(seatrightframe, image=greenimg, borderwidth=0, text=41, fg='white', font=medium_font, compound=CENTER, command=changecolor41)
seatlist.append(seatbtn41)
seatbtn42 = Button(seatrightframe, image=greenimg, borderwidth=0, text=42, fg='white', font=medium_font, compound=CENTER, command=changecolor42)
seatlist.append(seatbtn42)
seatbtn43 = Button(seatrightframe, image=greenimg, borderwidth=0, text=43, fg='white', font=medium_font, compound=CENTER, command=changecolor43)
seatlist.append(seatbtn43)
seatbtn44 = Button(seatrightframe, image=greenimg, borderwidth=0, text=44, fg='white', font=medium_font, compound=CENTER, command=changecolor44)
seatlist.append(seatbtn44)
seatbtn45 = Button(seatrightframe, image=greenimg, borderwidth=0, text=45, fg='white', font=medium_font, compound=CENTER, command=changecolor45)
seatlist.append(seatbtn45)
seatbtn46 = Button(seatrightframe, image=greenimg, borderwidth=0, text=46, fg='white', font=medium_font, compound=CENTER, command=changecolor46)
seatlist.append(seatbtn46)
seatbtn47 = Button(seatrightframe, image=greenimg, borderwidth=0, text=47, fg='white', font=medium_font, compound=CENTER, command=changecolor47)
seatlist.append(seatbtn47)
seatbtn48 = Button(seatrightframe, image=greenimg, borderwidth=0, text=48, fg='white', font=medium_font, compound=CENTER, command=changecolor48)
seatlist.append(seatbtn48)
seatbtn49 = Button(seatrightframe, image=greenimg, borderwidth=0, text=49, fg='white', font=medium_font, compound=CENTER, command=changecolor49)
seatlist.append(seatbtn49)
seatbtn50 = Button(seatrightframe, image=greenimg, borderwidth=0, text=50, fg='white', font=medium_font, compound=CENTER, command=changecolor50)
seatlist.append(seatbtn50)
seatbtn51 = Button(seatrightframe, image=greenimg, borderwidth=0, text=51, fg='white', font=medium_font, compound=CENTER, command=changecolor51)
seatlist.append(seatbtn51)
seatbtn52 = Button(seatrightframe, image=greenimg, borderwidth=0, text=52, fg='white', font=medium_font, compound=CENTER, command=changecolor52)
seatlist.append(seatbtn52)
seatbtn53 = Button(seatrightframe, image=greenimg, borderwidth=0, text=53, fg='white', font=medium_font, compound=CENTER, command=changecolor53)
seatlist.append(seatbtn53)
seatbtn54 = Button(seatrightframe, image=greenimg, borderwidth=0, text=54, fg='white', font=medium_font, compound=CENTER, command=changecolor54)
seatlist.append(seatbtn54)
seatbtn55 = Button(seatrightframe, image=greenimg, borderwidth=0, text=55, fg='white', font=medium_font, compound=CENTER, command=changecolor55)
seatlist.append(seatbtn55)
seatbtn56 = Button(seatrightframe, image=greenimg, borderwidth=0, text=56, fg='white', font=medium_font, compound=CENTER, command=changecolor56)
seatlist.append(seatbtn56)
#Function Seated Button
btnavailabel(seated)
seatbtn1.grid(row=0, column=0)
seatbtn2.grid(row=1, column=0)
seatbtn3.grid(row=2, column=0)
seatbtn4.grid(row=3, column=0)
seatbtn5.grid(row=3, column=1)
seatbtn6.grid(row=2, column=1)
seatbtn7.grid(row=1, column=1)
seatbtn8.grid(row=0, column=1)
seatbtn9.grid(row=0, column=2)
seatbtn10.grid(row=1, column=2)
seatbtn11.grid(row=2, column=2)
seatbtn12.grid(row=3, column=2)
seatbtn13.grid(row=3, column=3)
seatbtn14.grid(row=2, column=3)
seatbtn15.grid(row=1, column=3)
seatbtn16.grid(row=0, column=3)
seatbtn17.grid(row=0, column=4)
seatbtn18.grid(row=1, column=4)
seatbtn19.grid(row=2, column=4)
seatbtn20.grid(row=3, column=4)
seatbtn21.grid(row=3, column=5)
seatbtn22.grid(row=2, column=5)
seatbtn23.grid(row=1, column=5)
seatbtn24.grid(row=0, column=5)
seatbtn25.grid(row=0, column=6)
seatbtn26.grid(row=1, column=6)
seatbtn29.grid(row=0, column=0)
seatbtn30.grid(row=1, column=0)
seatbtn31.grid(row=2, column=0)
seatbtn32.grid(row=3, column=0)
seatbtn33.grid(row=3, column=1)
seatbtn34.grid(row=2, column=1)
seatbtn35.grid(row=1, column=1)
seatbtn36.grid(row=0, column=1)
seatbtn37.grid(row=0, column=2)
seatbtn38.grid(row=1, column=2)
seatbtn39.grid(row=2, column=2)
seatbtn40.grid(row=3, column=2)
seatbtn41.grid(row=3, column=3)
seatbtn42.grid(row=2, column=3)
seatbtn43.grid(row=1, column=3)
seatbtn44.grid(row=0, column=3)
seatbtn45.grid(row=0, column=4)
seatbtn46.grid(row=1, column=4)
seatbtn47.grid(row=2, column=4)
seatbtn48.grid(row=3, column=4)
seatbtn49.grid(row=3, column=5)
seatbtn50.grid(row=2, column=5)
seatbtn51.grid(row=1, column=5)
seatbtn52.grid(row=0, column=5)
seatbtn53.grid(row=0, column=6)
seatbtn54.grid(row=1, column=6)
seatbtn55.grid(row=2, column=6)
seatbtn56.grid(row=3, column=6)
#Blank Frame 2
seatblankframe2 = LabelFrame(findseatbodyframe, bg=grey, bd=0)
seatblankframe2.pack(fill=X, ipady=15)
#Find Seat Submit Button
findseatbtn = Button(findseatbodyframe, text="Next", fg="white", bg=blue, font=medium_font, command=userinfo)
findseatbtn.pack(ipadx=40)
#User Info Page Frame !!!!!!!!!!!!!!!!!!
userinfobodyframe = LabelFrame(containerframe, bd = 0, bg=grey)
#Blank Frame 1
customerinfoblankframe1 = LabelFrame(userinfobodyframe, bg=grey, bd=0)
customerinfoblankframe1.pack(fill=X, ipady=25)
userholderframe = LabelFrame(userinfobodyframe, highlightthickness=2, highlightbackground = blue, bg='white')
userholderframe.pack()
#Customer Info(1st Page)
firstpageframe = LabelFrame(userholderframe, bd=0, bg='white')
firstpageframe.pack()
#Progress Bar
progress1img = ImageTk.PhotoImage(Image.open('images/customerinfobar.png').resize((800, 100), Image.ANTIALIAS))
progresslabel = Label(firstpageframe, image=progress1img, bg='white')
progresslabel.grid(row=0, column=0, columnspan=3)
#Sub head 1 label
subhead1img = ImageTk.PhotoImage(Image.open('images/customerinfolabel.png').resize((160, 60), Image.ANTIALIAS))
subhead1label = Label(firstpageframe, image=subhead1img, bg='white')
subhead1label.grid(row=1, column=0, sticky='W', pady=5)
#Left-Mid-Right UserInfo Frame
userinfoleftframe = LabelFrame(firstpageframe, bg='white', bd=0)
userinfoleftframe.grid(row=2, column=0, pady=10)
userinfomidframe = LabelFrame(firstpageframe, bg='white')
userinfomidframe.grid(row=2, column=1, ipady=10, pady=10)
userinforightframe = LabelFrame(firstpageframe, bg='white', bd=0)
userinforightframe.grid(row=2, column=2, pady=10)
#Component
fullnamelabel = Label(userinfoleftframe, text="Full Name", bg='white', font=small_font)
fullnamelabel.grid(row=0, column=0)
fullnameentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
fullnameentry.grid(row=0, column=1, ipady=5, pady=12)
emaillabel = Label(userinfoleftframe, text="Email", bg='white', font=small_font)
emaillabel.grid(row=1, column=0)
emailentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
emailentry.grid(row=1, column=1, ipady=5, pady=12)
phonenumberlabel = Label(userinfoleftframe, text="Phone Number", bg='white', font=small_font)
phonenumberlabel.grid(row=2, column=0)
phonenumberentry = Entry(userinfoleftframe, font=small_font, highlightthickness=2, highlightbackground = blue)
phonenumberentry.grid(row=2, column=1, ipady=5, pady=12)
idpassportlabel = Label(userinforightframe, text="ID/Passport Number", bg='white', font=small_font)
idpassportlabel.grid(row=0, column=0)
idpassportentry = Entry(userinforightframe, font=small_font, highlightthickness=2, highlightbackground = blue)
idpassportentry.grid(row=0, column=1, ipady=5, pady=12)
emailconfirmlabel = Label(userinforightframe, text="Email Confirmation", bg='white', font=small_font)
emailconfirmlabel.grid(row=1, column=0)
emailconfirmentry = Entry(userinforightframe, font=small_font, highlightthickness=2, highlightbackground = blue)
emailconfirmentry.grid(row=1, column=1, ipady=5, pady=12)
userinfonextbtn = Button(firstpageframe, font=medium_font, text="Next", fg="white", bg=blue, command=payment)
userinfonextbtn.grid(row=3, column=0, columnspan=3, ipadx=15, pady=10)
#Payment Page(2nd Page)
secondpageframe = LabelFrame(userholderframe, bd=0, bg='white')
#Progress Bar
progress2img = ImageTk.PhotoImage(Image.open('images/paymentbar.png').resize((800, 100), Image.ANTIALIAS))
progress2label = Label(secondpageframe, image=progress2img, bg='white')
progress2label.grid(row=0, column=0)
#Sub head 2 label
subhead2img = ImageTk.PhotoImage(Image.open('images/paymentlabel.png').resize((160, 60), Image.ANTIALIAS))
subhead2label = Label(secondpageframe, image=subhead2img, bg='white')
subhead2label.grid(row=1, column=0, sticky='W', pady=5)
#Component page 2
r2 = IntVar()
Radiobutton(secondpageframe, text="Purchase offline(at gas station, postoffice)", font=medium_font, fg=blue, variable=r2, value=1, bg="white").grid(row=2, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by Naspas', font=medium_font, fg=blue, variable=r2, value=2, bg="white").grid(row=3, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by VNPay', font=medium_font, fg=blue, variable=r2, value=3, bg="white").grid(row=4, column=0, sticky='W', pady=5)
Radiobutton(secondpageframe, text='Purchase online by MOMO', font=medium_font, fg=blue, variable=r2, value=4, bg="white").grid(row=5, column=0, sticky='W', pady=5)
paymentnextbtn = Button(secondpageframe, font=medium_font, text="Next", fg="white", bg=blue, command=completed)
paymentnextbtn.grid(row=6, column=0, ipadx=15, pady=10)
#Completd Page(3rd Page)
thirdpageframe = LabelFrame(userholderframe, bd=0, bg='white')
#Progress Bar
progress3img = ImageTk.PhotoImage(Image.open('images/completedbar.png').resize((800, 100), Image.ANTIALIAS))
progress3label = Label(thirdpageframe, image=progress3img, bg='white')
progress3label.grid(row=0, column=0)
#Sub head 3 label
subhead3img = ImageTk.PhotoImage(Image.open('images/completedlabel.png').resize((160, 60), Image.ANTIALIAS))
subhead3label = Label(thirdpageframe, image=subhead3img, bg='white')
subhead3label.grid(row=1, column=0, sticky='W', pady=5)
#Component page 3
sucesspurchasedimg = ImageTk.PhotoImage(Image.open('images/successpurchased.png').resize((700, 70), Image.ANTIALIAS))
sucesspurchasedlabel = Label(thirdpageframe, image=sucesspurchasedimg, bg='white')
sucesspurchasedlabel.grid(row=2, column=0, pady=10)
endingpurchasesbtn = Button(thirdpageframe, font=medium_font, text="Back To Home Screen", fg="white", bg=blue, command=homepage)
endingpurchasesbtn.grid(row=3, column=0, pady=10)

#Start Admin Page!!!!!!!!!!!!!!!!
adminbodyframe = LabelFrame(containerframe, bg=grey, bd=0)
#Blank Frame 1
adminblankframe1 = LabelFrame(adminbodyframe, bg=grey, bd=0)
adminblankframe1.pack(fill=X, ipady=20)
#Holder
adminholderframe = LabelFrame(adminbodyframe, bg=grey, bd=0)
adminholderframe.pack(fill=BOTH, expand=YES)
#Blank Frame 2
adminblankframe2 = LabelFrame(adminbodyframe, bg=grey, bd=0)
adminblankframe2.pack(fill=X, ipady=20)
#Login
centerframe = LabelFrame(adminholderframe, bg='white')
centerframe.place(in_=adminholderframe, anchor="c", relx=.5, rely=.45)
labeladmin = Label(centerframe, text='Wellcome to Train Management System!', font=medium_font, bg="white")
labeladmin.grid(row=0, column=0, columnspan=2, padx=20, pady=(100, 0))
usernameloginlabel = Label(centerframe, text="Username", font=medium_font, bg='white')
usernameloginlabel.grid(row=1, column=0, pady=10)
usernameloginentry = Entry(centerframe, width=15, relief=RIDGE, font=medium_font, highlightthickness=1, highlightbackground = "blue")
usernameloginentry.grid(row=1, column=1, pady=10)
passwordloginlabel = Label(centerframe, text="Password", font=medium_font, bg='white')
passwordloginlabel.grid(row=2, column=0, pady=10)
passwordloginentry = Entry(centerframe, width=15, show='*', relief=RIDGE, font=medium_font, highlightthickness=1, highlightbackground = "blue")
passwordloginentry.grid(row=2, column=1, pady=10)
loginButton = Button(centerframe, text="Login", width=10, command=login, font=small_font)
loginButton.grid(row=3, column=0, columnspan=2, pady=10)
erropassLabel = Label(centerframe, text="", bg='white', fg='white', bd=0, font=medium_font)
erropassLabel.grid(row=4, column=0, columnspan=2, pady=10)
#Binding Press Enter to Login
usernameloginentry.bind('<Return>', lambda x:login())
passwordloginentry.bind('<Return>', lambda x:login())

#♥♥ Main Admin Page ♥♥
sidebarframe = LabelFrame(adminholderframe, bd=0, bg=lightedblue, width=150, height=500)
dashboardbtn = Button(sidebarframe, text="Dashboard", fg='white', bg=weightedblue, bd=0, font=med_large_font, command=dashboard)
dashboardbtn.pack(fill=X, pady=10)
traininfobtn = Button(sidebarframe, text="Train Infor", fg='white', bg=lightedblue, bd=0, font=med_large_font, command=traininfo)
traininfobtn.pack(fill=X, pady=10)
aboutbtn = Button(sidebarframe, text="About", fg='white', bg=lightedblue, font=med_large_font, bd=0, command=about)
aboutbtn.pack(fill=X, pady=10)

#Dashboard
dashboarddetailframe = LabelFrame(adminholderframe, bd=0, bg='white', width=850, height=500)
currenttrainframe = LabelFrame(dashboarddetailframe, bd=0, bg='white')
currenttrainframe.grid(row=0, column=0)
currenttrainlabel = Label(currenttrainframe, text='Current train running', font=med_large_font, bg='white', fg=blue)
currenttrainlabel.grid(row=0, column=0, padx=15, columnspan=3)
#First Trip
traintripframe1= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe1.grid(row=1, column=0, padx=15, pady=10)
traintripimg = ImageTk.PhotoImage(Image.open('images/traintrip.png').resize((240, 171), Image.ANTIALIAS))
traintripbtn1 = Button(traintripframe1, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn1.pack()
traincodelabel1 = Label(traintripframe1, text='SE1', font=small_font, bg='white')
traincodelabel1.place(x=20, y=5)
traintimelabel1 = Label(traintripframe1, text='17h00-20h00', font=small_font, bg='white')
traintimelabel1.place(x=100, y=5)
departlabel1 = Label(traintripframe1, text='Hanoi', font=small_font, bg='white')
departlabel1.place(x=100, y=40)
destilabel1 = Label(traintripframe1, text='Thanh Hoa', font=small_font, bg='white')
destilabel1.place(x=100, y=67)
availabel1 = Label(traintripframe1, text='56/56', font=small_font, bg='white')
availabel1.place(x=100, y=100)
#Second Trip
traintripframe2= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe2.grid(row=1, column=1, padx=15, pady=10)
traintripbtn2 = Button(traintripframe2, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn2.pack()
traincodelabel2 = Label(traintripframe2, text='SE1', font=small_font, bg='white')
traincodelabel2.place(x=20, y=5)
traintimelabel2 = Label(traintripframe2, text='17h00-20h00', font=small_font, bg='white')
traintimelabel2.place(x=100, y=5)
departlabel2 = Label(traintripframe2, text='Hanoi', font=small_font, bg='white')
departlabel2.place(x=100, y=40)
destilabel2 = Label(traintripframe2, text='Thanh Hoa', font=small_font, bg='white')
destilabel2.place(x=100, y=67)
availabel2 = Label(traintripframe2, text='56/56', font=small_font, bg='white')
availabel2.place(x=100, y=100)
#Third Trip
traintripframe3= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe3.grid(row=1, column=2, padx=15, pady=10)
traintripbtn3 = Button(traintripframe3, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn3.pack()
traincodelabel3 = Label(traintripframe3, text='SE1', font=small_font, bg='white')
traincodelabel3.place(x=20, y=5)
traintimelabel3 = Label(traintripframe3, text='17h00-20h00', font=small_font, bg='white')
traintimelabel3.place(x=100, y=5)
departlabel3 = Label(traintripframe3, text='Hanoi', font=small_font, bg='white')
departlabel3.place(x=100, y=40)
destilabel3 = Label(traintripframe3, text='Thanh Hoa', font=small_font, bg='white')
destilabel3.place(x=100, y=67)
availabel3 = Label(traintripframe3, text='56/56', font=small_font, bg='white')
availabel3.place(x=100, y=100)
#Forth Trip
traintripframe4= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe4.grid(row=2, column=0, padx=15, pady=10)
traintripbtn4 = Button(traintripframe4, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn4.pack()
traincodelabel4 = Label(traintripframe4, text='SE1', font=small_font, bg='white')
traincodelabel4.place(x=20, y=5)
traintimelabel4 = Label(traintripframe4, text='17h00-20h00', font=small_font, bg='white')
traintimelabel4.place(x=100, y=5)
departlabel4 = Label(traintripframe4, text='Hanoi', font=small_font, bg='white')
departlabel4.place(x=100, y=40)
destilabel4 = Label(traintripframe4, text='Thanh Hoa', font=small_font, bg='white')
destilabel4.place(x=100, y=67)
availabel4 = Label(traintripframe4, text='56/56', font=small_font, bg='white')
availabel4.place(x=100, y=100)
#Fifth Trip
traintripframe5= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe5.grid(row=2, column=1, padx=15, pady=10)
traintripbtn5 = Button(traintripframe5, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn5.pack()
traincodelabel5 = Label(traintripframe5, text='SE1', font=small_font, bg='white')
traincodelabel5.place(x=20, y=5)
traintimelabel5 = Label(traintripframe5, text='17h00-20h00', font=small_font, bg='white')
traintimelabel5.place(x=100, y=5)
departlabel5 = Label(traintripframe5, text='Hanoi', font=small_font, bg='white')
departlabel5.place(x=100, y=40)
destilabel5 = Label(traintripframe5, text='Thanh Hoa', font=small_font, bg='white')
destilabel5.place(x=100, y=67)
availabel5 = Label(traintripframe5, text='56/56', font=small_font, bg='white')
availabel5.place(x=100, y=100)
#Sixth Trip
traintripframe6= LabelFrame(currenttrainframe, bg='white', bd=0)
traintripframe6.grid(row=2, column=2, padx=15, pady=10)
traintripbtn6 = Button(traintripframe6, image=traintripimg, bg='white', bd=0, command=adminfindseat)
traintripbtn6.pack()
traincodelabel6 = Label(traintripframe6, text='SE1', font=small_font, bg='white')
traincodelabel6.place(x=20, y=5)
traintimelabel6 = Label(traintripframe6, text='17h00-20h00', font=small_font, bg='white')
traintimelabel6.place(x=100, y=5)
departlabel6 = Label(traintripframe6, text='Hanoi', font=small_font, bg='white')
departlabel6.place(x=100, y=40)
destilabel6 = Label(traintripframe6, text='Thanh Hoa', font=small_font, bg='white')
destilabel6.place(x=100, y=67)
availabel6 = Label(traintripframe6, text='56/56', font=small_font, bg='white')
availabel6.place(x=100, y=100)

#Seat Holder Container Frame
adminseatcontainerframe = LabelFrame(dashboarddetailframe, highlightthickness=2, highlightbackground = blue)
#56 Seats (VERY LAZY THIS PART!!!!)
#Left-Mid-Right Part Frame
adminseatleftframe = LabelFrame(adminseatcontainerframe, bd=0, bg=lightedgrey)
adminseatmidframe = LabelFrame(adminseatcontainerframe, bd=0, bg=lightedgrey)
adminseatrightframe = LabelFrame(adminseatcontainerframe, bd=0, bg=lightedgrey)
adminseatleftframe.grid(row=0, column=0)
adminseatmidframe.grid(row=0, column=1)
adminseatrightframe.grid(row=0, column=2)
#Seat Left Display
adminseatbtn1 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=1, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn1)
adminseatbtn2 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=2, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn2)
adminseatbtn3 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=3, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn3)
adminseatbtn4 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=4, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn4)
adminseatbtn5 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=5, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn5)
adminseatbtn6 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=6, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn6)
adminseatbtn7 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=7, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn7)
adminseatbtn8 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=8, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn8)
adminseatbtn9 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=9, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn9)
adminseatbtn10 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=10, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn10)
adminseatbtn11 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=11, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn11)
adminseatbtn12 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=12, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn12)
adminseatbtn13 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=13, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn13)
adminseatbtn14 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=14, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn14)
adminseatbtn15 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=15, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn15)
adminseatbtn16 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=16, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn16)
adminseatbtn17 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=17, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn17)
adminseatbtn18 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=18, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn18)
adminseatbtn19 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=19, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn19)
adminseatbtn20 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=20, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn20)
adminseatbtn21 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=21, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn21)
adminseatbtn22 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=22, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn22)
adminseatbtn23 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=23, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn23)
adminseatbtn24 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=24, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn24)
adminseatbtn25 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=25, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn25)
adminseatbtn26 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=26, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn26)
adminseatbtn27 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=27, fg='white', font=medium_font, compound=CENTER)
adminseatbtn27.grid(row=2, column=6)
adminseatlist.append(adminseatbtn27)
adminseatbtn28 = Button(adminseatleftframe, image=greenimg, borderwidth=0, text=28, fg='white', font=medium_font, compound=CENTER)
adminseatbtn28.grid(row=3, column=6)
adminseatlist.append(adminseatbtn28)
#Seat Mid Display
adminbarriel1label = Label(adminseatmidframe, image=barriel, bg=lightedgrey, bd=0)
adminbarriel2label = Label(adminseatmidframe, image=barriel, bg=lightedgrey, bd=0)
adminbarriel1label.pack()
adminbarriel2label.pack()
#Seat Right Display
adminseatbtn29 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=29, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn29)
adminseatbtn30 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=30, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn30)
adminseatbtn31 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=31, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn31)
adminseatbtn32 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=32, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn32)
adminseatbtn33 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=33, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn33)
adminseatbtn34 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=34, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn34)
adminseatbtn35 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=35, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn35)
adminseatbtn36 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=36, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn36)
adminseatbtn37 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=37, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn37)
adminseatbtn38 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=38, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn38)
adminseatbtn39 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=39, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn39)
adminseatbtn40 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=40, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn40)
adminseatbtn41 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=41, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn41)
adminseatbtn42 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=42, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn42)
adminseatbtn43 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=43, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn43)
adminseatbtn44 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=44, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn44)
adminseatbtn45 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=45, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn45)
adminseatbtn46 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=46, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn46)
adminseatbtn47 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=47, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn47)
adminseatbtn48 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=48, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn48)
adminseatbtn49 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=49, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn49)
adminseatbtn50 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=50, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn50)
adminseatbtn51 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=51, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn51)
adminseatbtn52 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=52, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn52)
adminseatbtn53 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=53, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn53)
adminseatbtn54 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=54, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn54)
adminseatbtn55 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=55, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn55)
adminseatbtn56 = Button(adminseatrightframe, image=greenimg, borderwidth=0, text=56, fg='white', font=medium_font, compound=CENTER)
adminseatlist.append(adminseatbtn56)
#Function Seated Button
adminbtnavailabel(seated1)
adminseatbtn1.grid(row=0, column=0)
adminseatbtn2.grid(row=1, column=0)
adminseatbtn3.grid(row=2, column=0)
adminseatbtn4.grid(row=3, column=0)
adminseatbtn5.grid(row=3, column=1)
adminseatbtn6.grid(row=2, column=1)
adminseatbtn7.grid(row=1, column=1)
adminseatbtn8.grid(row=0, column=1)
adminseatbtn9.grid(row=0, column=2)
adminseatbtn10.grid(row=1, column=2)
adminseatbtn11.grid(row=2, column=2)
adminseatbtn12.grid(row=3, column=2)
adminseatbtn13.grid(row=3, column=3)
adminseatbtn14.grid(row=2, column=3)
adminseatbtn15.grid(row=1, column=3)
adminseatbtn16.grid(row=0, column=3)
adminseatbtn17.grid(row=0, column=4)
adminseatbtn18.grid(row=1, column=4)
adminseatbtn19.grid(row=2, column=4)
adminseatbtn20.grid(row=3, column=4)
adminseatbtn21.grid(row=3, column=5)
adminseatbtn22.grid(row=2, column=5)
adminseatbtn23.grid(row=1, column=5)
adminseatbtn24.grid(row=0, column=5)
adminseatbtn25.grid(row=0, column=6)
adminseatbtn26.grid(row=1, column=6)
adminseatbtn29.grid(row=0, column=0)
adminseatbtn30.grid(row=1, column=0)
adminseatbtn31.grid(row=2, column=0)
adminseatbtn32.grid(row=3, column=0)
adminseatbtn33.grid(row=3, column=1)
adminseatbtn34.grid(row=2, column=1)
adminseatbtn35.grid(row=1, column=1)
adminseatbtn36.grid(row=0, column=1)
adminseatbtn37.grid(row=0, column=2)
adminseatbtn38.grid(row=1, column=2)
adminseatbtn39.grid(row=2, column=2)
adminseatbtn40.grid(row=3, column=2)
adminseatbtn41.grid(row=3, column=3)
adminseatbtn42.grid(row=2, column=3)
adminseatbtn43.grid(row=1, column=3)
adminseatbtn44.grid(row=0, column=3)
adminseatbtn45.grid(row=0, column=4)
adminseatbtn46.grid(row=1, column=4)
adminseatbtn47.grid(row=2, column=4)
adminseatbtn48.grid(row=3, column=4)
adminseatbtn49.grid(row=3, column=5)
adminseatbtn50.grid(row=2, column=5)
adminseatbtn51.grid(row=1, column=5)
adminseatbtn52.grid(row=0, column=5)
adminseatbtn53.grid(row=0, column=6)
adminseatbtn54.grid(row=1, column=6)
adminseatbtn55.grid(row=2, column=6)
adminseatbtn56.grid(row=3, column=6)
#Train Info
traininfodetailframe = LabelFrame(adminholderframe, bg='black', width=850, height=500, bd=0)
leftsidebarinfoframe = LabelFrame(traininfodetailframe, bg=bluegrey, width=150, height=500, bd=0)
leftsidebarinfoframe.pack(fill=BOTH, expand=YES, side=LEFT)
rightinfoframe = LabelFrame(traininfodetailframe, bg='red', width=700, height=500, bd=0)
rightinfoframe.pack(fill=BOTH, expand=YES, side=RIGHT)
#Sidebar Info
trainbtn = Button(leftsidebarinfoframe, text="Train", fg="black", bg=bluegrey, bd=0, font=med_large_font, command=train)
trainbtn.pack(fill=X, pady=10)
customerbtn = Button(leftsidebarinfoframe, text="Customer", fg='black', bg=bluegrey, bd=0, font=med_large_font, command=customer)
customerbtn.pack(fill=X, pady=10)
#Train Finding
trainfindingframe = LabelFrame(rightinfoframe, bd=0, bg='white', width=700, height=500)
typeoneormultiplelabel = Label(trainfindingframe, bd=0, bg='white', font=medium_font, text='Type one or multiple information below to for your search')
typeoneormultiplelabel.grid(row=0, column=0, columnspan=4, pady=15)
trainnamelabel = Label(trainfindingframe, bd=0, bg='white', font=small_font, text='Train Name')
trainnamelabel.grid(row=1, column=0, pady=15)
trainnameentry = Entry(trainfindingframe, bd=0, highlightthickness=2, highlightbackground = blue, font=medium_font)
trainnameentry.grid(row=1, column=1, pady=15)
routelabel = Label (trainfindingframe, bd=0, bg='white', font=small_font, text='Route')
routelabel.grid(row=1, column=2, padx=(20,0))
routeentry = Entry(trainfindingframe, bd=0, highlightthickness=2, highlightbackground = blue, font=medium_font)
routeentry.grid(row=1, column=3, pady=15)
confirmfindbtn = Button(trainfindingframe, text='CONFIRM', font=small_font, width=15, bg=lightedblue, bd=2, fg="white", command=listtrain)
confirmfindbtn.grid(row=2, column=0, columnspan=2, pady=15)
newtrainbtn = Button(trainfindingframe, text='NEW TRAIN', font=small_font, width=15, bg=green, bd=2, fg="white", command=newtrain)
newtrainbtn.grid(row=2, column=3, columnspan=2, pady=15)
#Train Table Frame
traintableframe = LabelFrame(trainfindingframe, bd=2, bg='white', highlightthickness=3, highlightbackground = "black")
traintableframe.grid(row=3, columnspan=4)
traintableimg = ImageTk.PhotoImage(Image.open('images/traintable.png').resize((650,45), Image.ANTIALIAS))
columntablelabel = Label(traintableframe, image=traintableimg, bg='white', bd=0)
columntablelabel.grid(row=0, column=0, columnspan=6)

#Customer Finding
customerfindingframe = LabelFrame(rightinfoframe, bd=0, bg='white', width=700, height=500)
typeoneormultiplelabel = Label(customerfindingframe, bd=0, bg='white', font=medium_font, text='Type one or multiple information below to for your search')
typeoneormultiplelabel.grid(row=0, column=0, columnspan=4, pady=15)
customernamelabel = Label(customerfindingframe, bd=0, bg='white', font=small_font, text='Name')
customernamelabel.grid(row=1, column=0, pady=15)
customernameentry = Entry(customerfindingframe, bd=0, highlightthickness=2, highlightbackground = blue, font=medium_font)
customernameentry.grid(row=1, column=1, pady=15)
customeridlabel = Label (customerfindingframe, bd=0, bg='white', font=small_font, text='ID/Passport')
customeridlabel.grid(row=1, column=2, padx=(20,0))
customeridentry = Entry(customerfindingframe, bd=0, highlightthickness=2, highlightbackground = blue, font=medium_font)
customeridentry.grid(row=1, column=3, pady=15)
customerconfirmfindbtn = Button(customerfindingframe, text='CONFIRM', font=small_font, width=15, bg=lightedblue, bd=2, fg="white", command=listcustomer)
customerconfirmfindbtn.grid(row=2, column=0, columnspan=2, pady=15)
#Customer Table Frame
customertableframe = LabelFrame(customerfindingframe, bd=2, bg='white', highlightthickness=3, highlightbackground = "black")
customertableframe.grid(row=3, columnspan=4)
customertableimg = ImageTk.PhotoImage(Image.open('images/customertable.png').resize((650,45), Image.ANTIALIAS))
customercolumntablelabel = Label(customertableframe, image=customertableimg, bg='white', bd=0)
customercolumntablelabel.grid(row=0, column=0, columnspan=6)

#Display Fixed Frame
containerframe.pack(fill=BOTH, expand=YES)
headerframe.pack(fill=X, side=TOP)
blankframe1.pack(fill=X, ipady=17)
menuframe.pack(fill=X)
homebodyframe.pack(fill=X)
footerframe.pack(fill=X, side=BOTTOM)

root.mainloop()
