# Generated by Django 3.2.2 on 2021-05-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0002_auto_20210516_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=120)),
                ('departing_time', models.DateTimeField()),
                ('number_of_cars', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
