# Generated by Django 3.2.2 on 2021-05-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=120, unique=True)),
                ('departing_time', models.DateTimeField()),
                ('number_of_seats', models.IntegerField(default=56)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
