# Generated by Django 3.2.2 on 2021-05-15 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(null=True), size=None),
        ),
    ]
