# Generated by Django 3.2.2 on 2021-05-15 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroute', '0004_alter_route_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None),
        ),
    ]
