# Generated by Django 3.2.2 on 2021-05-15 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroute', '0005_alter_route_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None)),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
